### ISSUE TITLE
Docker Configuration Problem

### ISSUE THREAD

**Issue by norinespears** [specify/specify7#1003]
I know you mentioned Ben was out this week, but I’ve hit another snag in trying to get the Docker implementation up on my test server using the all-in-one repo and I’m not sure if it’s my inexperience with Docker or missing instructions.  When I visit the root of the site in a browser at http://localhost, I get a 502 Bad Gateway error message from nginx.  

I’ve run the sudo docker-compose up -d from the all-in-one directory (even though the README for all-in-one says to run it from the just-specify7 directory) since I’m editing the docker-compose.yml file in that directory.  I’ve tried it with a minimal configuration with the specify7-worker, asset-server, report-runner and redis containers commented out and a full config.  In both cases, the all-in-one_specify7_1 container keeps restarting every few seconds.  This is the container that looks to be listening on port 8000, which most of the traffic from nginx is routed (if I’m understanding the nginx/specify.conf configuration correctly.)

I don’t have that much experience with Docker, but I’ve set the LOG_LEVEL to INFO and the SP7_DEBUG to true and then used sudo docker logs <container ID> for the all-in-one-specify7_1 image.  The initial lines of the log are:

```yaml
Updating static files in /volumes/static-files/.
Applying Django migrations.
```

It then runs through the following section twice, separated by a couple of seconds:

 
```yaml
[29/Sep/2021 16:23:01] [WARNING] [specifyweb.specify.load_datamodel:248] missing table or relationship setting dependent field: Deaccession.deaccessionpreparations

Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 88, in connect
    conn = self._new_conn()
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 70, in _new_conn
    self.source_address,
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 530, in urlopen
    raise MaxRetryError(self, url, e)
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='asset-server', port=8080): Max retries exceeded with url: /web_asset_store.xml (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
   url_patterns = getattr(resolver, 'url_patterns', [])
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/specify7/specifyweb/urls.py", line 12, in <module>
    from .context import urls as context_urls
  File "/opt/specify7/specifyweb/context/urls.py", line 3, in <module>
    from ..attachment_gw.views import get_settings as attachment_settings
  File "/opt/specify7/specifyweb/attachment_gw/views.py", line 193, in <module>
    init()
  File "/opt/specify7/specifyweb/attachment_gw/views.py", line 161, in init
    r = requests.get(settings.WEB_ATTACHMENT_URL)
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/opt/specify7/ve/lib/python3.6/site-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='asset-server', port=8080): Max retries exceeded with url: /web_asset_store.xml (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
```
 

After that, the whole sequence repeats (two lines of uploading static files and intiailizing Django followed by two identical sections of exceptions,) presumably because the container restarts.

I’m happy to send along our all-in-one/docker-compose.yml file.  Otherwise, I’m a little stumped as I followed the README.md instructions presented and don’t have enough Docker experience to troubleshoot from there.

**Comment by norinespears** [comment]
This was reported by Blaine at Duke. Max took a look and believes there is a configuration problem in the Sp 7 Production Docker Container.

**Comment by tlammer** [comment]
UTexas has also reported this problem

**Comment by benanhalt** [comment]
Probably the `ASSET_SERVER_URL` lines in the `specify7.environment` and `specify7-worker.environment`  sections need to be commented out. Specify 7 tries to talk to the asset server when if first starts up if that value is set.

**Comment by benanhalt** [comment]
This warning is normal. It is because of the changes in the deaccession / disposal related tables that were introduced in the 6.8.01 database schema. Basically there are some hard coded rules about these tables and in order to support both schema versions I had to include the rules for both versions. So in either case Specify 7 is going to notice some of the rule are inconsistent with the datamodel. The warning will go away once we decide to drop support for the 6.8.00 schema.

Sorry for the confusion. I'll create an issue to add a notice to the documentation that the warning is expected.

**Comment by ben3000** [comment]
> Could you share your `docker-compose.yml` file so i can see where possibly the issue is.

I'm trying to use `docker-compositions/all-in-one/docker-compose.yml`. Containers on my system already use ports 8080 and 3306 (plus others), so I'm tweaking the file to try and avoid these where necessary. Additionally, I'm running under WSL2 on Windows 10, which has [documented issues](https://abdus.dev/posts/fixing-wsl2-localhost-access-issue/) with linking the machine's "localhost" with Docker containers.

My `nginx/specify.conf` has the following at [line 3](https://github.com/specify/docker-compositions/blob/2be08f38b8a7c42fdc2e60fc2292317a92fe0359/all-in-one/nginx/specify.conf#L3):

`server_name host.docker.internal;`

My `docker-compose.yml` has the following at [line 30](https://github.com/specify/docker-compositions/blob/2be08f38b8a7c42fdc2e60fc2292317a92fe0359/all-in-one/docker-compose.yml#L30) and line 54:

`- ASSET_SERVER_URL=http://host.docker.internal:8089/web_asset_store.xml`

the following at line 70-71:

`- SERVER_NAME=host.docker.internal`
`- SERVER_PORT=8089`

and the following at line 84:

`- "8089:80"`

The site kinda works with a seed database supplied to us by Tim Noble, but there is a blank screen with "Specify is loading..." at the top no matter what Discipline I choose on the first screen after login.

The logs show output like:

`django.db.utils.OperationalError: (1054, "Unknown column 'agent.text3' in 'field list'")`

**Comment by ben3000** [comment]
Thanks, @PhatWheZ, the all-in-one Docker Compose file provides a Specify 6 container:
```
specify6:
  image: specifyconsortium/specify6-service:6.8.01
  volumes:
  - "specify6:/volumes/Specify
```
After running `docker-compose` with the all-in-one configuration, log output from that container shows:

> Updated Specify 6 in /volumes/Specify.

Do I need to install a separate Specify 6, or is this what you mean?

**Comment by PhatWheZ** [comment]
> Do I need to install a separate Specify 6, or is this what you mean?

I would encourage you installing Specify6 on your machine and performing this action once.
I can only speak to what my experience was.

If you dont come right ill try bring up the `docker-compose.yml` file for the all-in-one on a Windows 10 machine.

**Comment by FedorSteeman** [comment]
And yet I got the following error when I wanted to look up a specific specimen: 

> ProgrammingError at /api/delete_blockers/collectionobject/75753/
> (1146, "Table 'spsandbox.deaccessionpreparation' doesn't exist")

I hacked a workaround using the attached SQL, but this is not optimal. Did something go wrong with our database upgrade? 

[CreateTableDeaccessionPreparation.txt](https://github.com/specify/specify7/files/8897086/CreateTableDeaccessionPreparation.txt)

**Comment by FedorSteeman** [comment]
By comparing with another database, I noticed that the table simply was missing, so I just took the CREATE TABLE script from that one to fix the other. Perhaps something did go wrong during the database upgrade...
