### ISSUE TITLE
WB Validation exception: get() returned more than one Picklist -- it returned 2

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1064]
**Describe the bug**
An exception occurred during data set validation process.
I did not have this happen before with this data set, so it might just be a database issue

**To Reproduce**
1. Upload data set
2. Use mappings that are suggested by the automaker
3. Try to validate the data set

**Expected behavior**
Validation completes

**Screenshots**
![Screen Shot 2021-11-12 at 9 45 14 AM](https://user-images.githubusercontent.com/40512816/141494212-eff4cb86-9064-4922-be8a-3dcdcf18adb9.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Google Chrome
 - Specify 7 Version: `a11y` branch

**Additional context**
Data set: [test-workbench-data.csv.zip](https://github.com/specify/specify7/files/7528741/test-workbench-data.csv.zip)

Exception:
```sql
specify7-specify7-worker-1  | [2021-11-12 15:40:41,624: INFO/MainProcess] Received task: specifyweb.workbench.tasks.upload[7537d3a1-ef13-455d-a554-20be24a8e4fc]
specify7-specify7-worker-1  | [12/Nov/2021 15:40:43] [ERROR] [specifyweb.celery:30] Celery task failure!!!1
specify7-specify7-worker-1  | Traceback (most recent call last):
specify7-specify7-worker-1  |   File "/opt/specify7/ve/lib/python3.6/site-packages/celery/app/trace.py", line 405, in trace_task
specify7-specify7-worker-1  |     R = retval = fun(*args, **kwargs)
specify7-specify7-worker-1  |   File "/opt/specify7/ve/lib/python3.6/site-packages/celery/app/trace.py", line 697, in __protected_call__
specify7-specify7-worker-1  |     return self.run(*args, **kwargs)
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/tasks.py", line 41, in upload
specify7-specify7-worker-1  |     do_upload_dataset(collection, uploading_agent_id, ds, no_commit, allow_partial, progress)
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 113, in do_upload_dataset
specify7-specify7-worker-1  |     base_table, upload_plan = get_ds_upload_plan(collection, ds)
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 160, in get_ds_upload_plan
specify7-specify7-worker-1  |     return base_table, plan.apply_scoping(collection)
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/upload_table.py", line 29, in apply_scoping
specify7-specify7-worker-1  |     return apply_scoping(self, collection)
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 94, in apply_scoping_to_uploadtable
specify7-specify7-worker-1  |     toMany={f: [set_order_number(i, r.apply_scoping(collection)) for i, r in enumerate(rs)] for f, rs in ut.toMany.items()},
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 94, in <dictcomp>
specify7-specify7-worker-1  |     toMany={f: [set_order_number(i, r.apply_scoping(collection)) for i, r in enumerate(rs)] for f, rs in ut.toMany.items()},
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 94, in <listcomp>
specify7-specify7-worker-1  |     toMany={f: [set_order_number(i, r.apply_scoping(collection)) for i, r in enumerate(rs)] for f, rs in ut.toMany.items()},
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/tomany.py", line 20, in apply_scoping
specify7-specify7-worker-1  |     return apply_scoping(self, collection)
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 143, in apply_scoping_to_tomanyrecord
specify7-specify7-worker-1  |     wbcols={f: extend_columnoptions(colopts, collection, table.name, f) for f, colopts in tmr.wbcols.items()},
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 143, in <dictcomp>
specify7-specify7-worker-1  |     wbcols={f: extend_columnoptions(colopts, collection, table.name, f) for f, colopts in tmr.wbcols.items()},
specify7-specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 70, in extend_columnoptions
specify7-specify7-worker-1  |     picklist = picklistname and getattr(models, 'Picklist').objects.get(name=picklistname, collection=collection)
specify7-specify7-worker-1  |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
specify7-specify7-worker-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
specify7-specify7-worker-1  |   File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
specify7-specify7-worker-1  |     (self.model._meta.object_name, num)
specify7-specify7-worker-1  | specifyweb.specify.models.Picklist.MultipleObjectsReturned: get() returned more than one Picklist -- it returned 2!
specify7-specify7-worker-1  | [2021-11-12 15:40:43,244: ERROR/ForkPoolWorker-1] Task specifyweb.workbench.tasks.upload[7537d3a1-ef13-455d-a554-20be24a8e4fc] raised unexpected: MultipleObjectsReturned('get() returned more than one Picklist -- it returned 2!',)
s

```

Upload plan: 
```json
{
  "baseTableName": "collectionobject",
  "uploadable": {
    "uploadTable": {
      "wbcols": {},
      "static": {},
      "toOne": {
        "collectingevent": {
          "uploadTable": {
            "wbcols": {
              "startdate": "Start Date Collected",
              "enddate": "End Date Collected",
              "method": "Collection Method"
            },
            "static": {},
            "toOne": {
              "locality": {
                "uploadTable": {
                  "wbcols": {
                    "minelevation": "Min Depth (M)",
                    "maxelevation": "Max Depth (M)",
                    "latitude1": "Latitude1",
                    "latitude2": "Latitude2",
                    "longitude1": "Longitude1",
                    "longitude2": "Longitude2",
                    "latlongtype": "Lat Long Type"
                  },
                  "static": {},
                  "toOne": {
                    "geography": {
                      "treeRecord": {
                        "ranks": {
                          "Country": {
                            "treeNodeCols": {
                              "name": "Country"
                            }
                          },
                          "State": {
                            "treeNodeCols": {
                              "name": "State/Prov/Pref"
                            }
                          },
                          "Continent": {
                            "treeNodeCols": {
                              "name": "Continent/Ocean"
                            }
                          }
                        }
                      }
                    }
                  },
                  "toMany": {}
                }
              }
            },
            "toMany": {
              "collectors": [
                {
                  "wbcols": {},
                  "static": {},
                  "toOne": {
                    "agent": {
                      "uploadTable": {
                        "wbcols": {
                          "title": "Collector 1 Title",
                          "firstname": "Collector 1 First Name",
                          "middleinitial": "Collector 1 Middle Initial",
                          "lastname": "Collector 1 Last Name"
                        },
                        "static": {},
                        "toOne": {},
                        "toMany": {}
                      }
                    }
                  }
                },
                {
                  "wbcols": {},
                  "static": {},
                  "toOne": {
                    "agent": {
                      "uploadTable": {
                        "wbcols": {
                          "title": "Collector 2 Title",
                          "firstname": "Collector 2 First Name",
                          "middleinitial": "Collector 2 Middle Initial",
                          "lastname": "Collector 2 Last name"
                        },
                        "static": {},
                        "toOne": {},
                        "toMany": {}
                      }
                    }
                  }
                },
                {
                  "wbcols": {},
                  "static": {},
                  "toOne": {
                    "agent": {
                      "uploadTable": {
                        "wbcols": {
                          "title": "Collector 3 Title",
                          "firstname": "Collector 3 First Name",
                          "middleinitial": "Collector 3 Middle Initial",
                          "lastname": "Collector 3 Last Name"
                        },
                        "static": {},
                        "toOne": {},
                        "toMany": {}
                      }
                    }
                  }
                },
                {
                  "wbcols": {},
                  "static": {},
                  "toOne": {
                    "agent": {
                      "uploadTable": {
                        "wbcols": {
                          "title": "Collector 4 Title",
                          "firstname": "Collector 4 First Name",
                          "middleinitial": "Collector 4 Middle Initial",
                          "lastname": "Collector 4 Last Name"
                        },
                        "static": {},
                        "toOne": {},
                        "toMany": {}
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        "accession": {
          "uploadTable": {
            "wbcols": {
              "accessionnumber": "Accession No."
            },
            "static": {},
            "toOne": {},
            "toMany": {}
          }
        },
        "cataloger": {
          "uploadTable": {
            "wbcols": {
              "lastname": "Cataloged by"
            },
            "static": {},
            "toOne": {},
            "toMany": {}
          }
        }
      },
      "toMany": {
        "determinations": [
          {
            "wbcols": {
              "determineddate": "ID Date",
              "typestatusname": "ID Status"
            },
            "static": {},
            "toOne": {
              "taxon": {
                "treeRecord": {
                  "ranks": {
                    "Class": {
                      "treeNodeCols": {
                        "name": "Class"
                      }
                    },
                    "Family": {
                      "treeNodeCols": {
                        "name": "Family"
                      }
                    },
                    "Genus": {
                      "treeNodeCols": {
                        "name": "Genus"
                      }
                    },
                    "Species": {
                      "treeNodeCols": {
                        "name": "Species",
                        "author": "Species Author"
                      }
                    },
                    "Subspecies": {
                      "treeNodeCols": {
                        "name": "Subspecies",
                        "author": "Subspecies Author"
                      }
                    }
                  }
                }
              },
              "determiner": {
                "uploadTable": {
                  "wbcols": {
                    "firstname": "Who ID First Name",
                    "title": "Determiner 1 Title",
                    "middleinitial": "Determiner 1 Middle Initial",
                    "lastname": "Determiner 1 Last Name"
                  },
                  "static": {},
                  "toOne": {},
                  "toMany": {}
                }
              }
            }
          },
          {
            "wbcols": {},
            "static": {},
            "toOne": {
              "determiner": {
                "uploadTable": {
                  "wbcols": {
                    "firstname": "Determiner 1 First Name"
                  },
                  "static": {},
                  "toOne": {},
                  "toMany": {}
                }
              }
            }
          }
        ],
        "preparations": [
          {
            "wbcols": {},
            "static": {},
            "toOne": {
              "preptype": {
                "mustMatchTable": {
                  "wbcols": {
                    "name": "Prep Type 1"
                  },
                  "static": {},
                  "toOne": {},
                  "toMany": {}
                }
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by benanhalt** [comment]
This happens if the database has two picklists with the same name for a collection. There should be a uniqueness constraint on picklist name in the database schema to stop this from happening, but there isn't, so it does. Murphy.

**Comment by grantfitzsimmons** [comment]
Still having this issue. I have had it cause issues more than a couple of times, including today

**Comment by maxxxxxdlp** [comment]
Open query builder
Run a query on picklist table
Look for two picklists with the same `name`
Delete one of them

**Comment by grantfitzsimmons** [comment]
I did! It should have a uniqueness constraint in the future though

**Comment by maxxxxxdlp** [comment]
There is a duplicate pick list in FreshFish. Trying to make any changes to the duplicate causes a BusinessRuleException. Thus, there is some sort of uniqueness check.
Either duplicate pick list was created in an older Specify 7 version, or Specify 6 does not enforce uniqueness

<img width="1800" alt="Screen Shot 2022-05-12 at 19 43 51" src="https://user-images.githubusercontent.com/40512816/168189482-3632bdd6-70da-4b0a-ae0e-d49aa5c10282.png">

**Comment by maxxxxxdlp** [comment]
@benanhalt Andy pointed out that pick lists in Specify 6 are scoped down to a collection.
PIck list names must be unique within a collection, but don't have to be unique between collections.
Can you modify the business rules in Specify 7 to reflect that?

**Comment by benanhalt** [comment]
As you noted above, that business rule already exists. It can't do anything about duplicate name/collection pairs that are already in the database though.

**Comment by benanhalt** [comment]
If you change the duplicate to have a different name, you should be able to save it, I think.

**Comment by maxxxxxdlp** [comment]
That is indeed the case.
I am saying that Specify 6's business rule enforces uniqueness within collection only, not within the entire database.

**Comment by benanhalt** [comment]
It is with respect to collection.

**Comment by maxxxxxdlp** [comment]
@benanhalt It seems like Specify 6 is enforcing picklist uniqueness at the collection level, not the database level.

That causes an issue with Specify 6 resolving the correct picklist, but Specify 7 uses a picklist from the wrong database.

@benanhalt When I fetch a picklist, should I add `&domainfilter=true` to fetch pick lists for the current collection only? That seems to fix the issue like this - https://specifydev.slack.com/archives/CC6V12D3J/p1664804375295269

**Comment by grantfitzsimmons** [comment]
Samentha from Suriname reported this issue today

**Comment by grantfitzsimmons** [comment]
> That issue occurs anytime two pick lists have the same name in the database ([Issue #1064](https://github.com/specify/specify7/issues/1064)). The solution is to do the following:
> 
> 1. Open query builder
> 2. Run a query on the pick list table (e.g. https://sp7demofish.specifycloud.org/specify/query/new/picklist/, substitute your Specify URL in place of `sp7demofish.specifycloud.org`)
> 3. Look for two picklists with the same name
> 4. Delete or change the name for one of them
> 
> You will want to ensure that the pick list items associated with the pick list you keep are the desired ones!

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons do you have an idea of how people get to have duplicate pick lists?
Does sp6 and sp7 enforce pick list uniqueness differently?

**Comment by grantfitzsimmons** [comment]
Once Specify 6 has been retired, the schema config could:
- Show all pick list titles with the ID to the right in parenthesis
   - TypeStatus (1)
   - TypeStatus (2)
   - TaxonRank (3)
   - BiologicalSex (4)
   - BiologicalSex (5)
It could then be resolved based on the ID (WorkBench, forms, etc.) while the name is only shown in the UI

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons do you have an idea of how people get to have duplicate pick lists? Does sp6 and sp7 enforce pick list uniqueness differently?

Specify 6 and Specify 7 both enforce uniqueness the same. Sometimes something gets crossed and Specify can duplicate a pick list (even happens with system picklists). This isn't caught until something like this shows up most often.

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify7/issues/3897
Similar cause, due to matching pick list items instead of pick lists

**Comment by grantfitzsimmons** [comment]
**Reported By:** Matthew Cruz at The University of Michigan

Aug 30, 2023:
> Potential opportunity to clean up Herbarium Pickist for TypeStatus.
> 
> Details:
> 
> OOTB S6.8.03 + v7.8.13
> Botany Discipline
> Picklists
> 1. TypeStatus - 38 items
> 2. TypeStatus - 6 items
> 
> Determinations.typeStatusName uses the TypeStatus picklist with 6 items.

> ![image](https://github.com/specify/specify7/assets/37256050/07b295d2-d03e-4327-be61-7d3c9590a3fb)
>
>S7 does not even show the 38-item version in the list so I am not sure how someone could even use it anymore. I wonder though if it is still present in the OOTB configs because it needs to be present for legacy usage - maybe older collections refer to the 38-item picklist?

This could explain a **huge number** of the issues we've had with this. I'm so glad Matthew brought this to our attention!

See here:
**Instance 1:**
In the `config/botany/picklist.xml`:
https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/config/botany/picklist.xml#L13-L22

**Instance 2:**
In the `config/common/picklist.xml`:
https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/config/common/picklist.xml#L166-L207

This leads to default pick lists being **duplicated** in the database upon first configuration. 🤯 Will spin off into another issue.

**Comment by grantfitzsimmons** [comment]
Reported again by MCNB

**Comment by grantfitzsimmons** [comment]
Reported again by Bern
