### ISSUE TITLE
[a11y] Preferences is not working

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1182]
When attempting to access preferences, the following error occurs:

```
Unexpected Error

An unexpected error has occurred
Please reload the page and try again.
If this issue persists, please contact your IT support or if this is a Specify Cloud database, contact [support@specifysoftware.org](mailto:support@specifysoftware.org)

Error Message
TypeError: Cannot convert undefined or null to object

    at https://a11y.test.specifysystems.org/static/js/471.c97027387f780a5f2eae.bundle.js:1:789
    at c (https://a11y.test.specifysystems.org/static/js/main.781e9f8a90c6ac8ca79e.bundle.js:2:51405)
    at E (https://a11y.test.specifysystems.org/static/js/main.781e9f8a90c6ac8ca79e.bundle.js:2:26468)
```

Windows 10 & Safari, Edge

**Comment by maxxxxxdlp** [comment]
Fixed in 37c7c7fe9e35efdd78c9bae3ceb2c216c809f8a4
