### ISSUE TITLE
Error message when trying to delete a preparation linked to an interaction

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1431]
Reported by FWRI
To replicate:
Link a preparation to an interaction.  Try to delete the preparation.  Click Save
Specify appears to delete the preparation, but when you click Save, you get the message below.  Specify should either give a clearer message about what the issue is or, preferably, make the delete option inactive.
![image](https://user-images.githubusercontent.com/12532430/167217333-cf6445c6-b18b-4688-9e65-d8895813f183.png)
@benanhalt

**Comment by benanhalt** [comment]
Example exception from server log:
```
[06/May/2022 21:10:40] [ERROR] [django.request:228] Internal Server Error: /api/specify/collectionobject/367315/
Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/specify7/specifyweb/specify/views.py", line 20, in wrapped
    return view(request, *args, **kwargs)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/opt/specify7/specifyweb/specify/views.py", line 32, in wrapped
    return view(request, *args, **kwargs)
  File "/opt/specify7/specifyweb/specify/views.py", line 62, in view
    return dispatch_func(request, *args, **kwargs)
  File "/opt/specify7/specifyweb/specify/api.py", line 112, in resource_dispatch
    model, id, version, data)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/specify7/specifyweb/specify/api.py", line 568, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/opt/specify7/specifyweb/specify/api.py", line 592, in update_obj
    handle_to_many(collection, agent, obj, data)
  File "/opt/specify7/specifyweb/specify/api.py", line 537, in handle_to_many
    to_delete.delete()
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/models/query.py", line 710, in delete
    collector.collect(del_query)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/opt/specify7/specifyweb/specify/build_models.py", line 74, in protect
    models.PROTECT(collector, field, sub_objs, using)
  File "/opt/specify7/ve/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Preparation' because they are referenced through a protected foreign key: 'Loanpreparation.preparation'", <QuerySet [<Loanpreparation: Loanpreparation object (3514)>]>)
```

**Comment by benanhalt** [comment]
Exception should probably be trapped in `specifyweb/specify/views.py` and reported to the client as a BusinessRuleException.

**Comment by grantfitzsimmons** [comment]
Still able to recreate
