### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by jobdiogenes** [specify/specify7#205]
WARNING in ./bower_components/handsontable/dist/handsontable.full.js
Critical dependencies:
41:48-74 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./bower_components/handsontable/dist/handsontable.full.js 41:48-74

WARNING in ./bower_components/handsontable/dist/handsontable.full.js
Critical dependencies:
47:38-65 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./bower_components/handsontable/dist/handsontable.full.js 47:38-65

ERROR in ./~/css-loader!./css/main.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/specify/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/specify/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/home/specify/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/home/specify/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/loader.js:24:2)
 @ ./css/main.css 4:14-75

**Comment by benanhalt** [comment]
> ERROR in ./~/css-loader!./css/main.css
> Module build failed: ReferenceError: Promise is not defined

In my experience this is due to using an old version of NodeJS.

Right now, we are making extensive changes for a new version. I would recommend that you switch to the release branch which is intended for deployment.

```
git checkout release
```

**Comment by jobdiogenes** [comment]
Thank You,



2016-01-22 15:18 GMT-02:00 Ben Anhalt <notifications@github.com>:
