### ISSUE TITLE
Frontend not properly built while installing specify7

### ISSUE THREAD

**Issue by besi** [specify/specify7#217]
I tried to install specify7:

```bash
rm -fr specify7
git clone https://github.com/specify/specify7.git
cd specify7 && git checkout master && cd ..
pip install -r specify7/requirements.txt
echo "DEBUG = True" > specify7/specifyweb/settings/debug.py
make -C specify7 
cp ~/myspecifyconfig.py specify7/specifyweb/settings/specify_settings.py
python specify7/specifyweb/manage.py runserver
```

Now when specify starts up it looks like there are still dependencies that were not loaded:
![css-error](https://cloud.githubusercontent.com/assets/160412/13219758/5a13de8a-d972-11e5-82c8-e547374a49df.png)

```
Error: Cannot find module "!!./../node_modules/css-loader/index.js!./main.css"
webpackMissingModulemain.css:3
(anonymous function)main.css:3
__webpack_require__bootstrap e113491c5e3eb5e99ddb:46
(anonymous function)main.js:1
__webpack_require__bootstrap e113491c5e3eb5e99ddb:46
(anonymous function)bootstrap e113491c5e3eb5e99ddb:89
(anonymous function)bootstrap e113491c5e3eb5e99ddb:90
```

Internal reference `#11`

**Comment by besi** [comment]
This is the output I get when running 

```bash
$ make -C specify7
echo "VERSION = '`git describe`'" > specifyweb/settings/build_version.py
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C specifyweb/frontend/js_src
npm install
npm WARN package.json specify7-frontend@7.1.0 No description
npm WARN package.json specify7-frontend@7.1.0 No repository field.
npm WARN package.json specify7-frontend@7.1.0 No README data
npm WARN package.json backbone@0.9.10 No repository field.
node_modules/.bin/bower install
node_modules/.bin/webpack
Hash: e113491c5e3eb5e99ddb
Version: webpack 1.12.13
Time: 32399ms
          Asset     Size  Chunks             Chunk Names
      bundle.js  1.92 MB       0  [emitted]  main
    1.bundle.js   359 kB       1  [emitted]  welcome
    2.bundle.js  18.8 kB       2  [emitted]  treeview
    3.bundle.js  42.9 kB       3  [emitted]  wbview
    4.bundle.js  19.9 kB       4  [emitted]  wbimport
  bundle.js.map  2.67 MB       0  [emitted]  main
1.bundle.js.map   424 kB       1  [emitted]  welcome
2.bundle.js.map  34.9 kB       2  [emitted]  treeview
3.bundle.js.map  62.6 kB       3  [emitted]  wbview
4.bundle.js.map  43.4 kB       4  [emitted]  wbimport
  [48] ./lib/templates/formdeftemplate.html 467 bytes {0} [built]
  [49] ./lib/templates/formtabletemplate.html 739 bytes {0} [built]
  [50] ./lib/templates/formtemplate.html 381 bytes {0} [built]
  [51] ./lib/templates/viewwrappertemplate.html 336 bytes {0} [built]
  [52] ./lib/templates/attachmentview.html 418 bytes {0} [built]
  [91] ./lib/templates/querycbx.html 669 bytes {0} [built]
  [93] ./lib/templates/viewheader.html 1.36 kB {0} [built]
  [95] ./lib/templates/saveblocked.html 431 bytes {0} [built]
  [96] ./lib/templates/conflict.html 503 bytes {0} [built]
  [98] ./lib/templates/confirmdelete.html 396 bytes {0} [built]
 [106] ./lib/templates/latlonui.html 889 bytes {0} [built]
 [108] ./lib/templates/partialdateui.html 990 bytes {0} [built]
 [117] ./lib/templates/passwordchange.html 462 bytes {0} [built]
 [121] ./lib/templates/gmapplugin.html 419 bytes {0} [built]
 [128] ./lib/templates/subviewheader.html 912 bytes {0} [built]
 [143] ./lib/templates/queryfield.html 1.66 kB {0} [built]
 [159] ./lib/templates/wbtemplateeditor.html 812 bytes {0} [built]
 [167] ./lib/templates/welcome.html 686 bytes {1} [built]
 [168] ./lib/templates/aboutspecify.html 1.63 kB {1} [built]
 [171] ./lib/templates/othercollectionstemplate.html 375 bytes {0} [built]
 [173] ./lib/templates/querybuilder.html 1.1 kB {0} [built]
 [176] ./lib/templates/queryresults.html 432 bytes {0} [built]
 [193] ./lib/templates/wbview.html 1.03 kB {3} [built]
 [194] ./lib/templates/wbuploadstatus.html 433 bytes {3} [built]
 [195] ./lib/templates/wbuploaddetails.html 648 bytes {3} [built]
 [200] ./lib/templates/wbimport.html 1.26 kB {4} [built]
    + 176 hidden modules

ERROR in ./~/css-loader!./css/main.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/loader.js:24:2)
 @ ./css/main.css 4:14-75

ERROR in ./lib/wbview.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/handsontable/dist/handsontable.full.js in /Users/me/specify7/specifyweb/frontend/js_src/lib
 @ ./lib/wbview.js 9:19-42

ERROR in ./lib/wbview.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/papaparse/papaparse.js in /Users/me/specify7/specifyweb/frontend/js_src/lib
 @ ./lib/wbview.js 12:11-31

ERROR in ./lib/wbimport.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/papaparse/papaparse.js in /Users/me/specify7/specifyweb/frontend/js_src/lib
 @ ./lib/wbimport.js 11:11-31

ERROR in ./~/css-loader!./css/welcome.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/loader.js:24:2)
 @ ./css/welcome.css 4:14-78

ERROR in ./~/css-loader!./css/tree.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/loader.js:24:2)
 @ ./css/tree.css 4:14-75

ERROR in ./~/css-loader!./css/workbench.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/loader.js:24:2)
 @ ./css/workbench.css 4:14-80

ERROR in ./~/css-loader!./css/wbimport.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/loader.js:24:2)
 @ ./css/wbimport.css 4:14-79

ERROR in ./~/css-loader!./css/workbenchtemplateeditor.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/me/specify7/specifyweb/frontend/js_src/node_modules/css-loader/lib/loader.js:24:2)
 @ ./css/workbenchtemplateeditor.css 4:14-94
rm -rf ../static/css
cp -r css ../static/
```

**Comment by besi** [comment]
In `specifyweb/frontend/js_src/lib/main.js` the `main.css` is required like so:

```js
"use strict";
require ('../css/main.css');
```

So I checked if the file is available:

- <http://127.0.0.1:8000/css/main.css> **Not found**
- <http://127.0.0.1:8000/static/css/main.css> This works!

So the `main.js` seems to be looking for the `main.css` in the wrong spot.

**Comment by benanhalt** [comment]
I'm pretty sure the problem is that your version of *node* is too old. That has been the case for me, even with recent Ubuntu releases, and the symptom is the *css-loader* plugin failing with `ReferenceError: Promise is not defined`.

I have been using the *node* packages available at https://github.com/nodesource/distributions. I will add a note about this to the *README*.

**Comment by besi** [comment]
Thanks @benanhalt, I got it working now:

```bash
brew upgrade nodejs
make -C specify7
```
I had to manually update the secret in `/settings/secret_key.py` since the command `/dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 50` failed on my Mac.

**Sidenote**

While building I got the following errors:

```
ERROR in ./lib/wbview.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/handsontable/dist/handsontable.full.js in /Users/me/specify7/specifyweb/frontend/js_src/lib
 @ ./lib/wbview.js 9:19-42

ERROR in ./lib/wbview.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/papaparse/papaparse.js in /Users/me/specify7/specifyweb/frontend/js_src/lib
 @ ./lib/wbview.js 12:11-31

ERROR in ./lib/wbimport.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/papaparse/papaparse.js in /Users/me/specify7/specifyweb/frontend/js_src/lib
 @ ./lib/wbimport.js 11:11-31

ERROR in ./~/css-loader!./css/workbench.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../bower_components/handsontable/dist/handsontable.full.css in /Users/me/specify7/specifyweb/frontend/js_src/css
 @ ./~/css-loader!./css/workbench.css 3:10-120
```

**Comment by benanhalt** [comment]
Serving from Mac has not been a focus for us, so I'm surprised there are not more hang-ups. Those errors you are seeing seem to indicate the bower components didn't install. Those are all related to the workbench feature which is new in this upcoming release. If you are not planning to use that, you can probably ignore them.
