### ISSUE TITLE
Error when saving minimal collection object

### ISSUE THREAD

**Issue by besi** [specify/specify7#218]
I have added a new collection and when I want to save a new record I get the following error:

> An unexpected error has occured during communication with the server.

The server gives me this stacktrace:

```bash
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "~/me/specify7/specifyweb/../specifyweb/specify/views.py", line 23, in wrapped
    return view(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/cache.py", line 75, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "~/me/specify7/specifyweb/../specifyweb/specify/views.py", line 42, in view
    return dispatch_func(request, *args, **kwargs)
  File "~/me/specify7/specifyweb/../specifyweb/specify/api.py", line 166, in collection_dispatch
    request.GET.get('recordsetid', None))
  File "/Library/Python/2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "~/me/specify7/specifyweb/../specifyweb/specify/api.py", line 252, in post_resource
    obj = create_obj(collection, agent, name, data)
  File "~/me/specify7/specifyweb/../specifyweb/specify/api.py", line 328, in create_obj
    autonumber_and_save(collection, agent.specifyuser, obj)
  File "~/me/specify7/specifyweb/../specifyweb/specify/autonumbering.py", line 20, in autonumber_and_save
    for value in [getattr(obj, formatter.field_name.lower())]
AttributeError: 'NoneType' object has no attribute 'field_name'
```

I am not too familiar with django/python so my debugging is very limited, but I did dive into the error a bit and it looks like this error happens when `get_uiformatter` returns `None`.

I am happy to provide more information if necessary.

I am using the latest `master` branch.

**Comment by benanhalt** [comment]
Yeah, it looks like it is some bug related to a uiformatter that Specify 7 doesn't know how to handle. Is this database one that we at the Specify project converted for your institution? If we have a copy, I can try to replicate the error here and fix it.

**Comment by besi** [comment]
@benanhalt No this is a database I setup using the Specify6 fat client. However, I could send you an sql dump.

**Comment by benanhalt** [comment]
If you can send me an SQL dump that would probably be easiest. If it is just a few MB you can email it to me directly at anhalt@ku.edu. If it is too big, you can contact Theresa at specify@ku.edu, and she can tell you how to upload it to our dropbox.

If you don't want to send us the database, I can probably walk you through collecting enough information to sort it out.

**Comment by benanhalt** [comment]
@besi are you with UNBC?

**Comment by besi** [comment]
@benanhalt Thanks for your support. I did send you the dump (~5MB). No I am not with UNBC. I work with different Universities in Switzerland.

**Comment by benanhalt** [comment]
Ok. I have received the file and will let you know what I find out. I ask because UNBC just encountered the same (or very similar) problem. Coincidence I guess. Thanks.
