### ISSUE TITLE
Django migration fails with `Table 'django_content_type' already exists`

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2284]
Discovered in the BorrorLab's database

```
$ ./ve/bin/python manage.py migrate
Operations to perform:
  Apply all migrations: accounts, auth, contenttypes, notifications, permissions, sessions, workbench
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1050, "Table 'django_content_type' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/specify7/ve/lib/python3.8/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'django_content_type' already exists")

```

Content of `django_migrations` table:
<img width="708" alt="Screen Shot 2022-10-04 at 12 50 21" src="https://user-images.githubusercontent.com/40512816/193890483-966df1d0-bd7b-4762-8feb-38d125e993f9.png">

Content of `django_content_type` table:
<img width="708" alt="Screen Shot 2022-10-04 at 12 50 57" src="https://user-images.githubusercontent.com/40512816/193890583-b872ef34-dc22-4846-aa80-0c553f46f1b0.png">

Fixed by deleting the migration-related tables (they were empty) and re-running migrations.

Could it be that they created the tables manually without running migrations? Or did migrations fail after creating the tables, but before updating django_migrations

**Comment by benanhalt** [comment]
> Or did migrations fail after creating the tables, but before updating django_migrations

:point_up: 

It's a shortcoming of MySQL. It doesn't support for transactions for schema changes, so if it fails part way through... you get half a migration.

**Comment by grantfitzsimmons** [comment]
Migrations just need to be re-run to solve this problem. Can we close this issue?

@maxxxxxdlp

**Comment by maxxxxxdlp** [comment]
That would be a workaround, but not a solution.
Ben attempted to fix this in https://github.com/specify/specify7/pull/1037 - needs to be discussed, tested and merged
