### ISSUE TITLE
[testability] "Change Owner" option in WB results in error

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2582]
https://user-images.githubusercontent.com/103299204/206834884-76f49d66-5816-4d48-8a83-98aa1830127f.mp4

[Specify 7 Crash Report - 2022-12-10T06_06_49.488Z.txt](https://github.com/specify/specify7/files/10199303/Specify.7.Crash.Report.-.2022-12-10T06_06_49.488Z.txt)

https://uoregonpaleo-testability.test.specifysystems.org/specify/workbench/2/

**Comment by grantfitzsimmons** [comment]
```
Error

    at https://uoregonpaleo-testability.test.specifysystems.org/static/js/4388.4ae1d49ca6c799bf8fd3.bundle.js:1:10866
    at i (https://uoregonpaleo-testability.test.specifysystems.org/static/js/4388.4ae1d49ca6c799bf8fd3.bundle.js:1:235)
    at Suspense
    at a (https://uoregonpaleo-testability.test.specifysystems.org/static/js/main.4a071c2baddd8267cc84.bundle.js:2:78691)
    at y (https://uoregonpaleo-testability.test.specifysystems.org/static/js/main.4a071c2baddd8267cc84.bundle.js:2:34774)
```

I can recreate this bug. We should get this fixed before release.

---

https://unitecnov22-testability.test.specifysystems.org/specify/workbench/7/

Could recreate on this database as well

**Comment by grantfitzsimmons** [comment]
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/37256050/207071559-cbaccd53-5128-4bc0-bcb7-e0fa25d66631.png">

**Comment by melton-jason** [comment]
Fixed!
