### ISSUE TITLE
Extraneous spaces in 'in' type query field values causes error.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#275]

**Comment by benanhalt** [comment]
![image](https://cloud.githubusercontent.com/assets/287254/17070251/6d2f8198-5020-11e6-9e3a-720527fb971c.png)

```
Internal Server Error: /stored_query/ephemeral/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/specify7/specifyweb/../specifyweb/specify/views.py", line 23, in wrapped
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 115, in ephemeral
    data = run_ephemeral_query(request.specify_collection, request.specify_user, spquery)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 136, in run_ephemeral_query
    field_specs, limit, offset, recordsetid)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 183, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 217, in build_query
    collection=collection)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/queryfield.py", line 52, in add_to_query
    join_cache=join_cache)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/queryfieldspec.py", line 219, in add_to_query
    f = op(orm_field, value)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/query_ops.py", line 77, in op_in
    values = [self.format(v) for v in values.split(',')]
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/query_ops.py", line 37, in format
    return self.uiformatter.canonicalize(self.uiformatter.parse(value))
  File "/var/www/specify7/specifyweb/../specifyweb/specify/uiformatters.py", line 41, in parse
    raise ValueError("value doesn't match formatter")
ValueError: value doesn't match formatter
Internal Server Error: /stored_query/ephemeral/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/specify7/specifyweb/../specifyweb/specify/views.py", line 23, in wrapped
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 115, in ephemeral
    data = run_ephemeral_query(request.specify_collection, request.specify_user, spquery)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 136, in run_ephemeral_query
    field_specs, limit, offset, recordsetid)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 183, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/views.py", line 217, in build_query
    collection=collection)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/queryfield.py", line 52, in add_to_query
    join_cache=join_cache)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/queryfieldspec.py", line 219, in add_to_query
    f = op(orm_field, value)
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/query_ops.py", line 77, in op_in
    values = [self.format(v) for v in values.split(',')]
  File "/var/www/specify7/specifyweb/../specifyweb/stored_queries/query_ops.py", line 37, in format
    return self.uiformatter.canonicalize(self.uiformatter.parse(value))
  File "/var/www/specify7/specifyweb/../specifyweb/specify/uiformatters.py", line 41, in parse
    raise ValueError("value doesn't match formatter")
ValueError: value doesn't match formatter
[22/Jul/2016 05:45:20] "POST /stored_query/ephemeral/ HTTP/1.1" 500 5006
```

**Comment by garrettgirard** [comment]
Extraneous spaces are stripped upon entering the number, no error occurs.
