### ISSUE TITLE
Newly created ExportFeed is not recognized

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2862]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/37256050/213831659-20360ff1-f848-49e2-a3bb-555f049d5027.png">

https://kebryo20230118-edge.test.specifysystems.org/specify/resources/app-resource/23/

**Error when updating the RSS Feed:**
[nOaM7MPg.txt](https://github.com/specify/specify7/files/10471253/nOaM7MPg.txt)

```
"traceback":"Traceback (most recent call last):\n  File \"/opt/specify7/specifyweb/export/views.py\", line 169, in try_update_feed\n    update_feed(force=True, notify_user=user)\n  File \"/opt/specify7/specifyweb/export/feed.py\", line 37, in update_feed\n    raise MissingFeedResource()\nspecifyweb.export.feed.MissingFeedResource\n"}
```

I can export successfully when manually using the **Create DwC Archive** button in the user tools menu.

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/37256050/213831681-834c31ca-f7be-4d32-b2cb-7ed4a465a358.png">

New (left) and old (right). Only visible difference is the icon assigned to the resource.

<img width="2556" alt="image" src="https://user-images.githubusercontent.com/37256050/213831697-9318386e-191b-4664-ad81-37d1a7057317.png">

I removed the mimetype just to see if it makes a difference and it does not

**Comment by grantfitzsimmons** [comment]
I can't replicate this, but let's keep our eyes open in case this comes up again.

**Comment by grantfitzsimmons** [comment]
Same issue happened today!

Here's the full exception:

```
[16/Nov/2023 03:15:13] [ERROR] [specifyweb.export.views:172] update_feed failed: Traceback (most recent call last):
File "/opt/specify7/specifyweb/export/views.py", line 169, in try_update_feed update_feed (force=True, notify_user=user)
File "/opt/specify7/specifyweb/export/feed.py", line 37, in update_feed raise MissingFeedResource()
specifyweb.export.feed.MissingFeedResource
```

This happened on `uwfc` on `v7.9.1`.  I can create the export manually, but the configured `ExportFeed` is not working.

**Comment by grantfitzsimmons** [comment]
It's under `SpAppResourceDirID` `1`.  This is named `prefs`.

|SpAppResourceDirID|TimestampCreated|TimestampModified|Version|DisciplineType|IsPersonal|UserType|CreatedByAgentID|SpecifyUserID|CollectionID|ModifiedByAgentID|DisciplineID|
|------------------|----------------|-----------------|-------|--------------|----------|--------|----------------|-------------|------------|-----------------|------------|
|1|2020-10-08 18:36:39.000|2020-10-08 18:36:39.000|47||0|Prefs||1||||

**Comment by grantfitzsimmons** [comment]
This issue happened again. @CarolineDenis Even though the `Common` App Resource Directory exists, it assigned it to the `SpAppResourceDirID` `1` named `prefs`.

When creating a new `ExportFeed` app resource, it **needs** to put the `ExportFeed` in the `SpAppResourceDir` with the User Group (`userType`) `Common`, not `prefs`.

<img width="1038" alt="image" src="https://github.com/specify/specify7/assets/37256050/73fb2a7c-29cc-42b7-a648-0a0c4cc8248e">

**Comment by grantfitzsimmons** [comment]
Closing unless we can recreate
