### ISSUE TITLE
`DoesNotExist('Picklist matching query does not exist.')` when a field is mapped to an invalid picklist value

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3287]
**Describe the bug**

When validating/uploading a WorkBench data set, I am receiving the warning:

```
{
  "uploaderstatus": {
    "operation": "validating",
    "taskid": "0c1e7743-a477-4337-915e-2787099ef6fb"
  },
  "taskstatus": "FAILURE",
  "taskinfo": "DoesNotExist('Picklist matching query does not exist.')"
}
```

**To Reproduce**

**Data Set:** https://sp7demofish-edge.test.specifysystems.org/specify/workbench/5/
Username: `sp7demofish`, Collection: `KUFishTeaching`

1. Either navigate to the existing data set above or create a new WorkBench data set
2. Add Lat/Long Method in the Locality table
3. Attempt to validate or upload the data set

Full log from the worker process:

```
[2023-04-03 16:38:14,322: ERROR/ForkPoolWorker-1] Task specifyweb.workbench.tasks.upload[ffe36ff6-0aaf-4c8c-9449-8344eb0181ee] raised unexpected: DoesNotExist('Picklist matching query does not exist.')
Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/specify7/specifyweb/workbench/tasks.py", line 46, in upload
    do_upload_dataset(collection, uploading_agent_id, ds, no_commit, allow_partial, progress)
  File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 123, in do_upload_dataset
    base_table, upload_plan = get_ds_upload_plan(collection, ds)
  File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 188, in get_ds_upload_plan
    return base_table, plan.apply_scoping(collection)
  File "/opt/specify7/specifyweb/workbench/upload/upload_table.py", line 31, in apply_scoping
    return apply_scoping(self, collection)
  File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 93, in apply_scoping_to_uploadtable
    toOne={f: adjust_to_ones(u.apply_scoping(collection), f) for f, u in ut.toOne.items()},
  File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 93, in <dictcomp>
    toOne={f: adjust_to_ones(u.apply_scoping(collection), f) for f, u in ut.toOne.items()},
  File "/opt/specify7/specifyweb/workbench/upload/upload_table.py", line 31, in apply_scoping
    return apply_scoping(self, collection)
  File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 93, in apply_scoping_to_uploadtable
    toOne={f: adjust_to_ones(u.apply_scoping(collection), f) for f, u in ut.toOne.items()},
  File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 93, in <dictcomp>
    toOne={f: adjust_to_ones(u.apply_scoping(collection), f) for f, u in ut.toOne.items()},
  File "/opt/specify7/specifyweb/workbench/upload/upload_table.py", line 31, in apply_scoping
    return apply_scoping(self, collection)
  File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 91, in apply_scoping_to_uploadtable
    wbcols={f: extend_columnoptions(colopts, collection, table.name, f) for f, colopts in ut.wbcols.items()},
  File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 91, in <dictcomp>
    wbcols={f: extend_columnoptions(colopts, collection, table.name, f) for f, colopts in ut.wbcols.items()},
  File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 70, in extend_columnoptions
    picklist = picklistname and getattr(models, 'Picklist').objects.get(name=picklistname, collection=collection)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
specifyweb.specify.models.Picklist.DoesNotExist: Picklist matching query does not exist.
```

**Expected behavior**
I expected it to report the field that is causing the issue more clearly.

**Screenshots**

<img width="1392" alt="Screenshot 2023-04-03 at 11 42 39 AM" src="https://user-images.githubusercontent.com/37256050/229575707-54d8303c-9408-4e21-8a19-9e7f4e5a4567.png">

In the Schema Config, you can see that the `latLongMethod` field is assigned an invalid picklist value.

<img width="1392" alt="Screenshot 2023-04-03 at 11 42 43 AM" src="https://user-images.githubusercontent.com/37256050/229575728-87e788cf-c574-45ff-9540-5658fa860254.png">
<img width="389" alt="Screenshot 2023-04-03 at 11 42 45 AM" src="https://user-images.githubusercontent.com/37256050/229575798-ffbb51cb-6ae8-4dc2-9bda-40f33d7d9e33.png">

In the WorkBench data set, you can see that a column is mapped to that field with an invalid pick list:

<img width="1100" alt="Screenshot 2023-04-03 at 11 42 56 AM" src="https://user-images.githubusercontent.com/37256050/229575828-9b24047a-0dcc-4ce8-b811-8321a6dc7ff8.png">

**Desktop:**
 - OS: macOS Ventura 13.3
 - Browser: Firefox, Chrome
 - Specify 7 Version: `edge`(https://github.com/specify/specify7/commit/0345888388ccf2d0366c96117b3c58469e770b80)

**Database Name:** `sp7demofish`

**Reported By**
@carlosmbe

**Comment by emenslin** [comment]
Fixed
