### ISSUE TITLE
Collecting Trip Authorization deletion causes an error

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3951]
**Describe the bug**
Deleting a collecting trip authorization causes a crash.

**To Reproduce**
1. Go to `/specify/view/collectingtrip/10/`
2. Delete the 'eBird Checklists' record with no link in the web link field
3. Click **Save**

https://kubirds82523-v79-dev.test.specifysystems.org/specify/view/collectingtrip/10/

```
TypeError at /api/specify/collectingtrip/10/ cannot unpack non-iterable NoneType object Request Method: PUT Request URL: http://kubirds82523-v79-dev.test.specifysystems.org/api/specify/collectingtrip/10/ Django Version: 3.2.15 Python Executable: /opt/specify7/ve/bin/python3.8 Python Version: 3.8.0 Python Path: ['/opt/specify7', '/opt/specify7', '/opt/specify7/ve/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/specify7/ve/lib/python3.8/site-packages', '/opt/specify7'] Server time: Sat, 26 Aug 2023 02:16:46 -0500
```

[Specify 7 Crash Report - 2023-08-26T02 17 24.183Z.txt](https://github.com/specify/specify7/files/12444400/Specify.7.Crash.Report.-.2023-08-26T02.17.24.183Z.txt) 

**Expected behavior**

**Screenshots**

https://github.com/specify/specify7/assets/37256050/17242bb8-1daf-4153-b5c3-6d449e6f548f

<img width="990" alt="image" src="https://github.com/specify/specify7/assets/37256050/af134aa6-071d-449d-8a4a-982298aba8d8">

**Desktop:**
 - OS: macOS 14.0
 - Browser: Chrome and Firefox
 - Version: `v7.9-dev` and `v7.8.13`

**Database Name:** `KUBirds_8_25_23`

**Reported By**
Andy at KU

**Comment by grantfitzsimmons** [comment]
**500 error:**

```
TypeError at /api/specify/collectingtrip/10/
cannot unpack non-iterable NoneType object

Request Method: PUT
Request URL: http://kubirds82523-v79-dev.test.specifysystems.org/api/specify/collectingtrip/10/
Django Version: 3.2.15
Python Executable: /opt/specify7/ve/bin/python3.8
Python Version: 3.8.0
Python Path: ['/opt/specify7', '/opt/specify7', '/opt/specify7/ve/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/specify7/ve/lib/python3.8/site-packages', '/opt/specify7']
Server time: Sat, 26 Aug 2023 02:21:40 -0500
Installed Applications:
('django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.contenttypes',
 'django.contrib.auth',
 'specifyweb.specify',
 'specifyweb.permissions',
 'specifyweb.accounts',
 'specifyweb.stored_queries',
 'specifyweb.businessrules',
 'specifyweb.express_search',
 'specifyweb.context',
 'specifyweb.attachment_gw',
 'specifyweb.frontend',
 'specifyweb.barvis',
 'specifyweb.report_runner',
 'specifyweb.interactions',
 'specifyweb.workbench',
 'specifyweb.notifications',
 'specifyweb.export',
 'specifyweb.raven_placeholder')
Installed Middleware:
['django.middleware.gzip.GZipMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'specifyweb.context.middleware.ContextMiddleware',
 'specifyweb.permissions.middleware.PermissionsMiddleware',
 'specifyweb.middleware.general.GeneralMiddleware']


Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/specify7/specifyweb/specify/views.py", line 39, in wrapped
    return view(request, *args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/opt/specify7/specifyweb/specify/views.py", line 72, in view
    return dispatch_func(request, *args, **kwargs)
  File "/opt/specify7/specifyweb/specify/api.py", line 132, in resource_dispatch
    obj = put_resource(request.specify_collection,
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/specify7/specifyweb/specify/api.py", line 612, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/opt/specify7/specifyweb/specify/api.py", line 639, in update_obj
    handle_to_many(collection, agent, obj, data)
  File "/opt/specify7/specifyweb/specify/api.py", line 565, in handle_to_many
    rel_obj = update_obj(collection, agent,
  File "/opt/specify7/specifyweb/specify/api.py", line 635, in update_obj
    obj.save(force_update=True)
  File "/opt/specify7/specifyweb/specify/build_models.py", line 63, in save
    return super(model, self).save(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    pre_save.send(
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/specify7/specifyweb/businessrules/orm_signal_handler.py", line 19, in handler
    rule(sender, kwargs['instance'])
  File "/opt/specify7/specifyweb/businessrules/attachment_rules.py", line 27, in attachment_jointable_save
    obj.attachment.scopetype, obj.attachment.scopeid = Scoping(attachee)()

Exception Type: TypeError at /api/specify/collectingtrip/10/
Exception Value: cannot unpack non-iterable NoneType object
Request information:
USER: Specifyuser object (2)

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES:
csrftoken = 'lYEtJdAQ3FI1bvZeAv6Pbh4kXg2HiDWo4JE2TkLaIAK36F6HrSi3fMWLWEbwRmSo'
sessionid = '4ldmsmqccf2fwpz18yyxd01rahg457ev'
collection = '4'
```

**Comment by CarolineDenis** [comment]
I cannot reproduce this issue on xml-editor. Can someone else confirm and close this issue if the case? 
@specify/dev-testing @specify/testing @specify/developers

**Comment by carlosmbe** [comment]
## Reproduced in EDGE as of Jan 4, 2024

https://github.com/specify/specify7/assets/53784701/a1da74f4-a3c9-454c-a4dd-520150f79273


## Reproduced in 7.9

https://github.com/specify/specify7/assets/53784701/cd17e402-cb0a-4e63-96db-b075415fd9b2


## Reproduced in 7.8.13

https://github.com/specify/specify7/assets/53784701/6e1f3a23-1363-4f42-b040-232320fcfe2b

**Comment by melton-jason** [comment]
This is _very_ likely a duplicate of #3289

**Comment by emenslin** [comment]
Fixed
