### ISSUE TITLE
bug(QueryBuilder): Recursive formatters cause infinite recursion on the back-end

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#4292]
The following formatter works fine on the front-end as front-end climbs the tree until it reaches the Kingdom tree node and stops there:

![Screenshot 2023-12-14 at 21 30 46](https://github.com/specify/specify7/assets/40512816/44b56e9a-4cef-4112-8490-c1bd4630ddbe)

However, this fails on the back-end (possibly because it needs to construct an SQL query from it, rather than execute it on the fly)

Solutions:
1. See if we can support such recursive formatter
2. If not, fail gracefully (maybe stop recursion after 5 iterations, or something like that)

[Specify 7 Crash Report - 2023-12-15T05_29_59.018Z.txt](https://github.com/specify/specify7/files/13681392/Specify.7.Crash.Report.-.2023-12-15T05_29_59.018Z.txt)

```yaml
RecursionError at /stored_query/ephemeral/
maximum recursion depth exceeded

Request Method: POST
Request URL: http://localhost/stored_query/ephemeral/
Django Version: 3.2.15
Python Executable: /opt/specify7/ve/bin/python
Python Version: 3.8.0
Python Path: ['/opt/specify7', '/opt/specify7', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/specify7/ve/lib/python3.8/site-packages']
Server time: Fri, 15 Dec 2023 05:28:19 -0600
Installed Applications:
('django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.contenttypes',
 'django.contrib.auth',
 'specifyweb.specify',
 'specifyweb.permissions',
 'specifyweb.accounts',
 'specifyweb.stored_queries',
 'specifyweb.businessrules',
 'specifyweb.express_search',
 'specifyweb.context',
 'specifyweb.attachment_gw',
 'specifyweb.frontend',
 'specifyweb.barvis',
 'specifyweb.report_runner',
 'specifyweb.interactions',
 'specifyweb.workbench',
 'specifyweb.notifications',
 'specifyweb.export',
 'specifyweb.raven_placeholder')
Installed Middleware:
['django.middleware.gzip.GZipMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'specifyweb.context.middleware.ContextMiddleware',
 'specifyweb.permissions.middleware.PermissionsMiddleware',
 'specifyweb.middleware.general.GeneralMiddleware']


Traceback (most recent call last):
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/opt/specify7/specifyweb/specify/views.py", line 35, in wrapped
    return view(request, *args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/specify7/specifyweb/stored_queries/views.py", line 82, in ephemeral
    data = run_ephemeral_query(collection, request.specify_user, spquery)
  File "/opt/specify7/specifyweb/stored_queries/execution.py", line 405, in run_ephemeral_query
    return execute(session, collection, user, tableid, distinct, count_only,
  File "/opt/specify7/specifyweb/stored_queries/execution.py", line 540, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid=recordsetid, formatauditobjs=formatauditobjs, distinct=distinct)
  File "/opt/specify7/specifyweb/stored_queries/execution.py", line 620, in build_query
    query, field, predicate = fs.add_to_query(query, formatauditobjs=formatauditobjs)
  File "/opt/specify7/specifyweb/stored_queries/queryfield.py", line 49, in add_to_query
    return self.fieldspec.add_to_query(query, value=self.value, op_num=None if no_filter else self.op_num, negate=self.negate, formatter=self.format_name, formatauditobjs=formatauditobjs)
  File "/opt/specify7/specifyweb/stored_queries/queryfieldspec.py", line 202, in add_to_query
    query, orm_field = query.objectformatter.objformat(query, getattr(models, self.root_table.name), formatter)
  File "/opt/specify7/specifyweb/stored_queries/format.py", line 167, in objformat
    query, value, expr = make_case(query, caseNode)
  File "/opt/specify7/specifyweb/stored_queries/format.py", line 157, in make_case
    query, expr, _ = make_expr(query, node.text, node.attrib)
  File "/opt/specify7/specifyweb/stored_queries/format.py", line 129, in make_expr
    query, expr = self.objformat(query, table, formatter_name)
  File "/opt/specify7/specifyweb/stored_queries/format.py", line 167, in objformat
    query, value, expr = make_case(query, caseNode)
...
```

**Comment by realVinayak** [comment]
[the backend fixes](https://github.com/specify/specify7/tree/xml-editor-backend-fixes) monkey patches it by bailing out. This specific case might be non-trivial to implement, but a solution would be to make a join `taxontreedefitem` times (so all for all ranks as we can't guess the rank of a node before hand) and adding case when clause to every taxon table in the path for the switch fields.
