### ISSUE TITLE
Make django_migrations error

### ISSUE THREAD

**Issue by badernageral** [specify/specify7#439]
Hi, after run 'make all' i've got the output:

`/usr/bin/python manage.py migrate notifications
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/specify7/specifyweb/specify/models.py", line 3, in <module>
    from .datamodel import datamodel
  File "/var/www/specify7/specifyweb/specify/datamodel.py", line 3, in <module>
    datamodel = load_datamodel()
  File "/var/www/specify7/specifyweb/specify/load_datamodel.py", line 141, in load_datamodel
    flag_dependent_fields(datamodel)
  File "/var/www/specify7/specifyweb/specify/load_datamodel.py", line 161, in flag_dependent_fields
    field = table.get_field(fieldname)
AttributeError: 'NoneType' object has no attribute 'get_field'
Makefile:21: recipe for target 'django_migrations' failed
make: *** [django_migrations] Error 1
`

The database user have DDL rights.

**Comment by benanhalt** [comment]
This is usually caused by Specify 7 using an old version of Specify 6. Check the `THICK_CLIENT_LOCATION` value in `local_specify_settings.py`. It needs to be pointing to a v6.6.06 installation of Specify 6.

**Comment by badernageral** [comment]
Hi @benanhalt, you are right, my Specify 6 files are in the wrong version, thank you!
