### ISSUE TITLE
Specify 7 adds invalid business rule references to new form definitions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4815]
**Describe the bug**
`edge` introduces a bug when using the visual editor to create a form definition for the "ExsiccataItem" table. The generated XML includes a reference to non-existent business rules (`edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules`), causing Specify 6 to crash when trying to open the form.

*Impact:* Users who create forms with the Specify 7 visual editor and then try to open those forms in Specify 6 will encounter a crash.

*Cause:* The visual editor in Specify 7 incorrectly adds a `busrules` attribute to the `<view>` element in the generated XML for the "ExsiccataItem" form definition. This attribute references a Java class that doesn't exist, leading to the crash in Specify 6.

*Workaround:*
1. *Use manual editing:* Manually create the form definition for "ExsiccataItem" in Specify 7 using the XML editor. This avoids the bug introduced by the visual editor.

---

While it appears that the `busrules` reference was assumed to be safe for most popular tables, many tables in the model that can have form definitions lack a dedicated `{TableName}BusRules.java` file and do not have associated rules.

https://github.com/specify/specify6/tree/master/src/edu/ku/brc/specify/datamodel/busrules

After searching the entirety of the `config` directory in Specify 6, no references to `edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules` were found.

<img width="244" alt="image" src="https://github.com/specify/specify7/assets/37256050/36915862-25a1-443e-9864-60b966bcc4d8">

@melton-jason Can you confirm this to be the underlying issue?

This issue does not cause problems in Specify 7 but prevents Specify 6 from opening forms with these invalid rules.

**To Reproduce**

You'll need to have this database accessible in both Specify 6 and 7, or you'll need to make a backup of the database after performing the XML editing steps in 7 for use in Specify 6.

**Specify 7:**
1. Go to any form definition
2. Use the visual editor
3. Check the "Show All Tables" button
4. Go to `Exsiccata Item` in the table list
5. Create a new form based on the `Botany > Manager > Botany` `ExsiccataItem` definition
   <img width="692" alt="image" src="https://github.com/specify/specify7/assets/37256050/8c8890c3-99a1-4abf-9106-e5c3693c05f8">
6. Create and save it. Remember the name assigned to this view definition.
7. Save the form definition.
8. Go to the view definition currently being used for Collection Object.
9. Add this row to the Collection Object form, replacing the `viewname` with the name of the view definition created above if it was changed from the default.
   ```xml
   <row>
      <cell type="subview" id="8" name="exsiccataItems" viewname="ExsiccataItem" defaulttype="table" colspan="13"/>
   </row>
    ```
7. Save the form definition.
8. Verify the forms appear and work well in Specify 7 (they should!) 😊 

<img width="1266" alt="image" src="https://github.com/specify/specify7/assets/37256050/bcd52c1c-4aec-44b3-ac62-eb9e09e8ac07">

**Specify 6:**
10. Launch Specify 6 using this same form definition logged in as the same user.
11. Try to open the Collection Object form
12. See that it does not open and rather does nothing.

<img width="2560" alt="image" src="https://github.com/specify/specify7/assets/37256050/74bc70dc-4bb0-414f-858f-ff70ca04cc4a">

In the [Specify log](https://discourse.specifysoftware.org/t/how-to-send-an-error-or-specify-log-file/771), you should see this:
```
************************ Type: App  Action: StartUp
10:06:50 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
10:06:50 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
10:06:50  INFO brc.specify.Specify:2376 - positionAndFitToScreen(javax.swing.JFrame[frame0,244,93,1024x796,hidden,layout=java.awt.BorderLayout,title=Specify 6.8.03,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,28,1024x768,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true], 703, -1078, 1280, 944)
10:06:52  WARN brc.ui.UIRegistry:533 - Couldn't find key[Save] in resource bundle [resources]
The field 'mod' (modifier) is hidden in the schema and shouldn't be used on the Form 'Collection Object'.
The field '9' (confidence) is hidden in the schema and shouldn't be used on the Form 'Determination'.
The field '8' (qualifier) is hidden in the schema and shouldn't be used on the Form 'Determination'.
The field 'an' (alternateName) is hidden in the schema and shouldn't be used on the Form 'Determination'.
The field '9' (confidence) is hidden in the schema and shouldn't be used on the Form 'Determination Table'.
The field '8' (qualifier) is hidden in the schema and shouldn't be used on the Form 'Determination Table'.
The field 'an' (alternateName) is hidden in the schema and shouldn't be used on the Form 'Determination Table'.
The field '2' (text2) is hidden in the schema and shouldn't be used on the Form 'Collection Object'.
Exception in thread "AWT-EventQueue-0" java.lang.InternalError: Can't instantiate BusinessRulesIFace [edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules]
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:298)
	at edu.ku.brc.af.ui.forms.FormViewObj.<init>(FormViewObj.java:341)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2588)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:253)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2881)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:979)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:935)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:258)
	at edu.ku.brc.af.ui.forms.ViewFactory.createItem(ViewFactory.java:1995)
	at edu.ku.brc.af.ui.forms.ViewFactory.processRows(ViewFactory.java:2194)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2602)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:253)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2881)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:979)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:935)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:280)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:146)
	at edu.ku.brc.af.tasks.subpane.FormPane.createForm(FormPane.java:426)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:196)
	at edu.ku.brc.specify.tasks.DataEntryTask.openView(DataEntryTask.java:292)
	at edu.ku.brc.specify.tasks.DataEntryTask.processDataEntryCommands(DataEntryTask.java:1836)
	at edu.ku.brc.specify.tasks.DataEntryTask.doCommand(DataEntryTask.java:2367)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.af.core.NavBoxAction.actionPerformed(NavBoxAction.java:179)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:291)
	... 57 more
```

The underlying issue is that Specify 6 does not recognize `ExsiccataItemBusRules`, and Specify 7 is adding a reference to these non-existent business rules in the form definition.

## Explanation
I confirmed that manually adding the `ExsiccataItem` `<view>` and `<viewdef>` did not result in this issue, but using the visual editor made it inaccessible in Specify 6. When extracting both sections (the manual and automatically created ones), I saw this:

**Added manually in XML editor in Specify 7:**
```xml
        <view name="ExsiccataItem"
            class="edu.ku.brc.specify.datamodel.ExsiccataItem"
            resourcelabels="false">
            <desc><![CDATA[Project form.]]></desc>
            <altviews>
                <altview name="ExsiccataItem View" viewdef="ExsiccataItem" mode="view"/>
                <altview name="ExsiccataItem Edit" viewdef="ExsiccataItem" mode="edit" default="true"/>
            </altviews>
        </view>
		<viewdef name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
			<desc>Form for ExsiccataItem</desc>
			<!--columnDef>p,2px,p,2px,100px,2px,p,2px,100px,2px,100px,p:g</columnDef-->
			<columnDef>p,2px,100px,2px,p,2px,100px,2px,p,p:g</columnDef>
			<rowDef auto="true" sep="2px" cell="p"/>
			<rows>
				<row>
					<cell type="label" labelfor="exsiccata"/>
					<cell type="field" id="exsiccata" name="exsiccata" uitype="querycbx" initialize="name=Exsiccata" colspan="5"/>
				</row>
				<row>
					<cell type="label" labelfor="1"/>
					<cell type="field" id="1" name="fascicle" uitype="text"/>
					<cell type="label" labelfor="2"/>
					<cell type="field" id="2" name="number" uitype="text"/>
				</row>
			</rows>
		</viewdef>
```

**WORKING manually defined definition:** [ManualExsiccataItem.xml.zip](https://github.com/specify/specify7/files/15065155/ManualExsiccataItem.xml.zip)

**Created by the Visual Editor in Specify 7:**
```xml
		<view name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" resourcelabels="false" busrules="edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules">
			<desc>Project form.</desc>
			<altviews>
				<altview name="ExsiccataItem View" viewdef="ExsiccataItem" mode="view"/>
				<altview name="ExsiccataItem Edit" viewdef="ExsiccataItem" mode="edit" default="true"/>
			</altviews>
		</view>
		<viewdef name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
			<desc>Form for ExsiccataItem</desc>
			<!--columnDef>p,2px,p,2px,100px,2px,p,2px,100px,2px,100px,p:g</columnDef-->
			<columnDef>p,2px,100px,2px,p,2px,100px,2px,p,p:g</columnDef>
			<rowDef auto="true" sep="2px" cell="p"/>
			<rows>
				<row>
					<cell type="label" labelfor="exsiccata"/>
					<cell type="field" id="exsiccata" name="exsiccata" uitype="querycbx" initialize="name=Exsiccata" colspan="5"/>
				</row>
				<row>
					<cell type="label" labelfor="1"/>
					<cell type="field" id="1" name="fascicle" uitype="text"/>
					<cell type="label" labelfor="2"/>
					<cell type="field" id="2" name="number" uitype="text"/>
				</row>
			</rows>
		</viewdef>
```

**BUGGED Visual editor defined definition:** [BUGVisualExsiccataItem.xml.zip](https://github.com/specify/specify7/files/15065161/BUGVisualExsiccataItem.xml.zip)

Nothing of note is different between these two aside from one **very** important thing. In the `<view>` section, you can see a reference to a set of business rules:

```
<view name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" resourcelabels="false" busrules="edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules">
```

Presumably, Specify 6 reads this and fails to instantiate `BusinessRulesIFace` as this rule doesn't exist as a `java` file in the `src/edu/ku/brc/specify/datamodel/busrules` directory.

https://github.com/specify/specify6/tree/master/src/edu/ku/brc/specify/datamodel/busrules

**Crash Report**
[Specify 7 System Information - 2024-04-22T15_26_39.984Z.txt](https://github.com/specify/specify7/files/15065168/Specify.7.System.Information.-.2024-04-22T15_26_39.984Z.txt)

Please, also fill out the following information manually:

- OS: macOS
- Browser: Arc
- Specify 7 Version: `edge`
- Database Name: `ku_vascplant` (local)
- Collection name: KU Vascular Plant
- User Name: spadmin

**Comment by grantfitzsimmons** [comment]
Same can be observed with other tables resulting in the same failure. Any table that is not listed in [this directory](https://github.com/specify/specify6/tree/master/src/edu/ku/brc/specify/datamodel/busrules) will cause Specify 6 to fail if the `<view>` is automatically created by Specify 7 using the visual editor.

<img width="727" alt="image" src="https://github.com/specify/specify7/assets/37256050/da6cc6c0-bf32-4568-9bb1-fe73ad671464">

**Comment by grantfitzsimmons** [comment]
[ListOfBusRules.txt](https://github.com/specify/specify7/files/15065412/ListOfBusRules.txt)
