### ISSUE TITLE
Column 'TableID' cannot be null

### ISSUE THREAD

**Issue by shuaiscott** [specify/specify7#52]
I don't know if this is the best place to report Specify 7 errors, but here goes. Everything works when adding data to a Collection Object and when viewing existing attachments, but when you add an attachment, I got this error:

```bash
No handlers could be found for logger "specifyweb.specify.api"
Internal Server Error: /api/specify/collectionobject/4/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/specify7/specifyweb/../specifyweb/specify/views.py", line 21, in wrapped
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 75, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/specify7/specifyweb/../specifyweb/specify/views.py", line 40, in view
    return dispatch_func(request, *args, **kwargs)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 105, in resource_dispatch
    model, id, version, data)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 463, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 484, in update_obj
    handle_to_many(collection, agent, obj, data)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 438, in handle_to_many
    rel_obj = create_obj(collection, agent, rel_model, rel_data, parent_obj=obj)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 315, in create_obj
    handle_to_many(collection, agent, obj, data)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 438, in handle_to_many
    rel_obj = create_obj(collection, agent, rel_model, rel_data, parent_obj=obj)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 304, in create_obj
    handle_fk_fields(collection, agent, obj, data)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 392, in handle_fk_fields
    parent_obj=obj)
  File "/specify7/specifyweb/../specifyweb/specify/api.py", line 309, in create_obj
    autonumber_and_save(collection, agent.specifyuser, obj)
  File "/specify7/specifyweb/../specifyweb/specify/autonumbering.py", line 36, in autonumber_and_save
    obj.save()
  File "/specify7/specifyweb/../specifyweb/specify/build_models.py", line 52, in save
    return super(model, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1673, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 127, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'TableID' cannot be null")
[20/Jan/2015 13:34:51] "PUT /api/specify/collectionobject/4/ HTTP/1.1" 500 4570
```

**Comment by benanhalt** [comment]
Hi Scott. If you go to the Specify 7 welcome page in your installation and click on the "Specify 7" logo at the bottom, it will bring up an "About Specify" dialog. Can you paste the system information from that here?

**Comment by shuaiscott** [comment]
System Information
Version:	v7.0.0-5-g6dc2276(debug)
Specify 6 Version:	6.6.00
Database Version:	6.6.00
Schema Version:	2.1

**Comment by benanhalt** [comment]
The TableID column was added to Attachment table in a previous Specify 6 release. The NOT NULL constraint was not added by the upgrade process, so the constraint is only present on newly created databases. This means the bug did not appear on upgraded testing databases. I was able to replicate by adding the NOT NULL constraint.

A fix has been committed to the master branch. Please reopen if the bug is still present for you after pulling the latest commit.

Thanks for the report.

**Comment by shuaiscott** [comment]
Works great! Thanks for the fix.
