### ISSUE TITLE
Can't roll back `003_cotype_picklist` migration

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5319]
When running  `ve/bin/python manage.py migrate specify 0003_cotype_picklist`, I get this:

```
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Splocalecontaineritem' because they are referenced through protected foreign keys: 'Splocaleitemstr.itemdesc'.", {<Splocaleitemstr: Splocaleitemstr object (36643)>})
```

```
Operations to perform:
  Target specific migration: 0003_cotype_picklist, from specify
Running migrations:
  No migrations to apply.
  Your models in app(s): 'specify' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
specify@b1f499091d50:/opt/specify7$
specify@b1f499091d50:/opt/specify7$ ve/bin/python manage.py migrate specify 0002_geo
Operations to perform:
  Target specific migration: 0002_geo, from specify
Running migrations:
  Rendering model states... DONE
  Unapplying specify.0003_cotype_picklist...Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/migration.py", line 174, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 196, in database_backwards
    self.reverse_code(from_state.apps, schema_editor)
  File "/opt/specify7/specifyweb/specify/migrations/0003_cotype_picklist.py", line 75, in revert_migration
    revert_cotype_splocalecontaineritem(apps)
  File "/opt/specify7/specifyweb/specify/migrations/0003_cotype_picklist.py", line 61, in revert_cotype_splocalecontaineritem
    Splocalecontaineritem.objects.filter(name=FIELD_NAME, container__name='collectionobject', container__schematype=0).delete()
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 745, in delete
    collector.collect(del_query)
  File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Splocalecontaineritem' because they are referenced through protected foreign keys: 'Splocaleitemstr.itemdesc'.", {<Splocaleitemstr: Splocaleitemstr object (36643)>})
specify@b1f499091d50:/opt/specify7$
```

This is on the container `specify7-test-panel-kufish51623-issue-114-backend-1` on the test panel.

DB: `kufish51623`
Version: `issue-114-backend`

`root@ip-172-31-30-145:~# docker exec -it specify7-test-panel-kufish51623-issue-114-backend-1 /bin/bash`

**Comment by grantfitzsimmons** [comment]
@sharadsw I actually was able to roll this back successfully on a new database, so I am happy to close this if you find it isn't a problem

**Comment by sharadsw** [comment]
@grantfitzsimmons Awesome! The migration should be reversible as long as there's only 1 co -> cotype schema config entry in the db. I think previously we had multiple migrations that added that entry because of which this migration wasn't reversible
