### ISSUE TITLE
"Invalid Picklist" causes a vague validation error in the workbench.

### ISSUE THREAD

**Issue by alesan99** [specify/specify7#5328]
**Describe the bug**
If a field in the schema config is set to a picklist that doesn't exist (appears to happen on database creation), the workbench validation stops abruptly with a vague error.

**To Reproduce**

1. Look for a field in schema config that is set to Pick List and displays (current, invalid value). You probably can cause this by manually changing it through sql as well.
2. Create a workbench mapping with the field
3. Attempt to validate.
4. You should see an error.

**Expected behavior**
The error should be handled in a clearer and more elegant way. Something like the problem column turning red with the error "Picklist is invalid value".

**Screenshots**
See the invalid selected picklist here:
![chrome_9PxD6GU1pB](https://github.com/user-attachments/assets/d78c6250-9c92-4823-bd13-66dee7ec0487)
This causes an error during workbench validation that can be hard to track down:

https://github.com/user-attachments/assets/4a485cf4-6b87-4164-b3ac-439cf1caa551

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: 7.9.6.2
- Database Name: Newly created databases

```specify7-worker-1  | Traceback (most recent call last):
specify7-worker-1  |   File "/opt/specify7/ve/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
specify7-worker-1  |     R = retval = fun(*args, **kwargs)
specify7-worker-1  |   File "/opt/specify7/ve/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
specify7-worker-1  |     return self.run(*args, **kwargs)
specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/tasks.py", line 43, in upload
specify7-worker-1  |     do_upload_dataset(collection, uploading_agent_id, ds, no_commit, allow_partial, progress)
specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 126, in do_upload_dataset
specify7-worker-1  |     base_table, upload_plan = get_ds_upload_plan(collection, ds)
specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/upload.py", line 190, in get_ds_upload_plan
specify7-worker-1  |     return base_table, plan.apply_scoping(collection)
specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/upload_table.py", line 33, in apply_scoping
specify7-worker-1  |     return apply_scoping_to_uploadtable(self, collection)
specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 128, in apply_scoping_to_uploadtable
specify7-worker-1  |     wbcols={f: extend_columnoptions(colopts, collection, table.name, f) for f, colopts in ut.wbcols.items()},
specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 128, in <dictcomp>
specify7-worker-1  |     wbcols={f: extend_columnoptions(colopts, collection, table.name, f) for f, colopts in ut.wbcols.items()},
specify7-worker-1  |   File "/opt/specify7/specifyweb/workbench/upload/scoping.py", line 104, in extend_columnoptions
specify7-worker-1  |     picklist = picklists[0] if len(collection_picklists) == 0 else collection_picklists[0]
specify7-worker-1  |   File "/opt/specify7/ve/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
specify7-worker-1  |     return qs._result_cache[0]
specify7-worker-1  | IndexError: list index out of range
specify7-worker-1  | [2024-10-17 14:15:11,125: ERROR/ForkPoolWorker-2] Task specifyweb.workbench.tasks.upload[bfbea947-befc-49d4-b5ce-27d81bb9e228] raised unexpected: IndexError('list index out of range')```

**Comment by grantfitzsimmons** [comment]
@alesan99 – Can you provide an example database for this?

Importantly, that pick list might not be invalid. Does it exist in another collection in the same discipline? If so, you must switch to that collection to edit it.

**Comment by alesan99** [comment]
> @alesan99 – Can you provide an example database for this?
> 
> Importantly, that pick list might not be invalid. Does it exist in another collection in the same discipline? If so, you must switch to that collection to edit it.

Update the issue with a link to an example database. Freshly created and no changes made aside from starting a workbench upload.

Looks like the picklist was never created.
