### ISSUE TITLE
Server error when collectionobject has no current determinations.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#547]
Observed by uw-geo-collections when opening loans.

Exception is: 
```
[15/Oct/2019 17:01:16] [ERROR] [django.request:124] Internal Server Error: /api/specify/collectionobject/23715/
Traceback (most recent call last):
  File "/home/specify/servers/uw-geo-collections/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/servers/uw-geo-collections/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/servers/uw-geo-collections/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/servers/uw-geo-collections/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/servers/uw-geo-collections/Specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/uw-geo-collections/Specify7/ve/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/specify/servers/uw-geo-collections/Specify7/specifyweb/specify/views.py", line 30, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/uw-geo-collections/Specify7/specifyweb/specify/views.py", line 44, in view
    return dispatch_func(request, *args, **kwargs)
  File "/home/specify/servers/uw-geo-collections/Specify7/specifyweb/specify/api.py", line 95, in resource_dispatch
    data = get_resource(model, id, request.GET.get('recordsetid', None))
  File "/home/specify/servers/uw-geo-collections/Specify7/specifyweb/specify/api.py", line 202, in get_resource
    data = obj_to_data(obj)
  File "/home/specify/servers/uw-geo-collections/Specify7/specifyweb/specify/api.py", line 617, in obj_to_data
    data['currentdetermination'] = currDets[0] if len(dets) > 0 else None;
IndexError: list index out of range
```

**Comment by benanhalt** [comment]
Cherry picked into specifycloud.
