### ISSUE TITLE
Attachments can't be added to Taxa

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#559]
Discovered in fwri.specifycloud.org.

It is due to the relationship between taxontreedef and discipline being reversed from what is expected to the scope lookup fails.

Fixing this raises the question of how to scope an attachment to a taxon if the taxon tree is used by multiple disciplines. Maybe use the next higher scope?

```
[12/Dec/2019 12:12:26] [ERROR] [django.request:124] Internal Server Error: /api/specify/taxon/5760/
Traceback (most recent call last):
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/views.py", line 30, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/views.py", line 44, in view
    return dispatch_func(request, *args, **kwargs)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/api.py", line 108, in resource_dispatch
    model, id, version, data)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/api.py", line 524, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/api.py", line 547, in update_obj
    handle_to_many(collection, agent, obj, data)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/api.py", line 486, in handle_to_many
    rel_obj = create_obj(collection, agent, rel_model, rel_data, parent_obj=obj)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/api.py", line 332, in create_obj
    autonumber_and_save(collection, agent.specifyuser, obj)
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/autonumbering.py", line 41, in autonumber_and_save
    obj.save()
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/build_models.py", line 55, in save
    return super(model, self).save(*args, **kwargs)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/db/models/base.py", line 820, in save_base
    update_fields=update_fields)
  File "/home/specify/servers/fwri/Specify7/ve/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/specify/servers/fwri/Specify7/specifyweb/businessrules/orm_signal_handler.py", line 19, in handler
    rule(sender, kwargs['instance'])
  File "/home/specify/servers/fwri/Specify7/specifyweb/businessrules/attachment_rules.py", line 25, in attachment_jointable_save
    obj.attachment.scopetype, obj.attachment.scopeid = Scoping(attachee)()
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/scoping.py", line 15, in __call__
    return getattr(self, table, lambda: None)()
  File "/home/specify/servers/fwri/Specify7/specifyweb/specify/scoping.py", line 66, in taxon
    return DISCIPLINE_SCOPE, self.obj.definition.discipline_id
AttributeError: 'Taxontreedef' object has no attribute 'discipline_id'

```

**Comment by grantfitzsimmons** [comment]
Still being requested by FWRI today

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Should we disable the Taxon Attachments button or view if this is the case? I cannot test attachments without an attachment server so I think it might be wise to at least disable this feature

**Comment by benanhalt** [comment]
Actually I was wrong before. TaxonTreeDef -> Discipline is one-to-one so the fix was trivial.
