### ISSUE TITLE
`/opt/Specify/` does not exist

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#563]
I have the following issue while trying to `make all` developer's branch of Specify 7

![Screenshot from 2020-01-16 15-21-23](https://user-images.githubusercontent.com/40512816/72571251-e570f080-3873-11ea-8338-73463e0bb059.png)
```
WARNING in ./bower_components/handsontable/dist/handsontable.full.js
Critical dependencies:
41:48-74 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./bower_components/handsontable/dist/handsontable.full.js 41:48-74

WARNING in ./bower_components/handsontable/dist/handsontable.full.js
Critical dependencies:
47:38-65 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./bower_components/handsontable/dist/handsontable.full.js 47:38-65
make[1]: Leaving directory '/home/specify/Downloads/specify7/specifyweb/frontend/js_src'
/home/specify/Downloads/specify7/specify7/ve/bin/python manage.py migrate notifications
^[[BTraceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/specify/Downloads/specify7/specifyweb/specify/models.py", line 2, in <module>
    from .check_versions import check_versions
  File "/home/specify/Downloads/specify7/specifyweb/specify/check_versions.py", line 6, in <module>
    from .specify_jar import specify_jar
  File "/home/specify/Downloads/specify7/specifyweb/specify/specify_jar.py", line 6, in <module>
    specify_jar = ZipFile(os.path.join(settings.SPECIFY_THICK_CLIENT, 'specify.jar'))
  File "/usr/lib/python2.7/zipfile.py", line 779, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/opt/Specify/specify.jar'
make: *** [Makefile:21: django_migrations] Error 1
```

Seems like the issue is connected with me not having the `/opt/Specify` directory. Is this directory supposed to be created by itself, or am I supposed to create it?

**Comment by maxxxxxdlp** [comment]
Fixed that with `sudo cp ~/Specify/* /opt/Specify/` . **Should it be mentioned in `README.md`?**

Now I get this issue:
![Screenshot from 2020-01-16 15-40-18](https://user-images.githubusercontent.com/40512816/72572228-b740e000-3876-11ea-817d-7acafd74c8ef.png)

```
make[1]: Leaving directory '/home/specify/Downloads/specify7/specifyweb/frontend/js_src'
/usr/bin/python manage.py migrate notifications
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 61, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 263, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'MasterUser'@'localhost' (using password: YES)")
make: *** [Makefile:21: django_migrations] Error 1

```

`sudo !!` does not help (it causes an error with `bower` not being able to run with sudo, but that error can be fixed by adding `--allow-root option` in `specifyweb/frontend/js_src/node_modules/Makefile:5`, but I get the same `Access denied...` problem still)

**Comment by maxxxxxdlp** [comment]
Fixed both issues by editing the `local_specify_settings.py` file
