### ISSUE TITLE
Error when validating data set

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#576]
Internal Server Error when trying to validate the dataset

![Screenshot from 2020-01-17 10-50-47](https://user-images.githubusercontent.com/40512816/72637976-443b7600-3917-11ea-9191-87268b58b9e5.png)

![Screenshot from 2020-01-17 10-49-15](https://user-images.githubusercontent.com/40512816/72637975-443b7600-3917-11ea-9f2c-5515f7d9fb45.png)

```
[17/Jan/2020 12:48:55] "GET /api/specify/sptasksemaphore/?domainfilter=false&taskname=WORKBENCHUPLOAD&islocked=True&offset=0 HTTP/1.1" 200 69
Internal Server Error: /api/workbench/validate/2/skip/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 30, in wrapped
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/workbench/views.py", line 210, in upload
    with open(os.path.join(settings.WB_UPLOAD_LOG_DIR, output_file), "w") as f:
IOError: [Errno 2] No such file or directory: u'/var/cache/specify_wb_upload/specify7_2_2b2382cc-9358-4338-bce6-8942a146a987'
```

Seems to be connected with file not existing
The `/var/cache/specify/` directory does not exist on my drive

**Comment by maxxxxxdlp** [comment]
It does not happen when tested on the biwebdbtest.nhm.ku.edu. Probably I have misconfigured my local Specify 7. I had a lot of issues with it that did not happen anywhere else
