### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#578]
I received an error connected to invalid syntax

![Screenshot from 2020-01-17 12-29-46](https://user-images.githubusercontent.com/40512816/72644323-997e8400-3925-11ea-9995-fd9f17207b49.png)
```
make[1]: Leaving directory '/home/specify/Downloads/specify7/specifyweb/frontend/js_src'
/home/specify/Downloads/specify7/specify7/ve/bin/python manage.py migrate notifications
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/specify/Downloads/specify7/specifyweb/businessrules/models.py", line 1, in <module>
    from . import (
  File "/home/specify/Downloads/specify7/specifyweb/businessrules/interaction_rules.py", line 5, in <module>
    from specifyweb.specify.api import parse_uri
  File "/home/specify/Downloads/specify7/specifyweb/specify/api.py", line 448
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
make: *** [Makefile:21: django_migrations] Error 1
```

Seems to happen in here:

![Screenshot from 2020-01-17 12-29-53](https://user-images.githubusercontent.com/40512816/72644322-997e8400-3925-11ea-8303-e0c17289e060.png)

Fixed by commenting out that section:

![Screenshot from 2020-01-17 12-32-37](https://user-images.githubusercontent.com/40512816/72644321-997e8400-3925-11ea-9608-7c1f74c890d5.png)

Can it be connected to me having both versions of specify and using virtual environment?

![Screenshot from 2020-01-17 12-35-31](https://user-images.githubusercontent.com/40512816/72644468-ee21ff00-3925-11ea-9a08-67df07a770cb.png)

**Comment by benanhalt** [comment]
That is from a bad merge. You did a `git pull` with a dirty working tree.
