### ISSUE TITLE
Error on autocomplete

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#579]
I receive an error within short time after entering anything into the `Accession #` field

![Screenshot from 2020-01-17 12-49-10](https://user-images.githubusercontent.com/40512816/72645200-e2373c80-3927-11ea-8fc1-18ef266a6c40.png)

![Screenshot from 2020-01-17 12-48-57](https://user-images.githubusercontent.com/40512816/72645201-e2373c80-3927-11ea-89a5-9c9bf61f78c3.png)

```
Internal Server Error: /notifications/messages/
Traceback (most recent call last):
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/notifications/views.py", line 21, in get_messages
    for m in messages
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1146, "Table 'specify4.notifications_message' doesn't exist")
```

I would suppose the issue happens when Specify 7 tries to query the database to get the list of available Accessions

**Comment by maxxxxxdlp** [comment]
In some databases I get this error message in addition to the previously reported one when performing same actions 

![Screenshot from 2020-01-20 06-15-56](https://user-images.githubusercontent.com/40512816/72733302-708c0800-3b4c-11ea-8c8a-eacb537067b3.png)

```
Traceback (most recent call last):
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/views.py", line 56, in ephemeral
    data = run_ephemeral_query(request.specify_collection, request.specify_user, spquery)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 377, in run_ephemeral_query
    field_specs, limit, offset, recordsetid, formatauditobjs=format_audits)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 442, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid=recordsetid, formatauditobjs=formatauditobjs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 505, in build_query
    query, field = fs.add_to_query(query, formatauditobjs=formatauditobjs)
TypeError: add_to_query() got an unexpected keyword argument 'formatauditobjs'
[20/Jan/2020 08:15:31] "POST /stored_query/ephemeral/ HTTP/1.1" 500 7197
Internal Server Error: /notifications/messages/
```

Seems to happen in various parts of Specify. It is just that the case with autocomplete is the only one that shows this error message to the user, where as in all other cases, the error is reported in the terminal only

**Comment by maxxxxxdlp** [comment]
I tried manually solving this issue by executing `CREATE TABLE notifications_message (column_name TEXT NOT NULL);`

Here is the error I get in that case (probably connected to me not creating proper columns):
```
Internal Server Error: /stored_query/ephemeral/
Traceback (most recent call last):
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/views.py", line 56, in ephemeral
    data = run_ephemeral_query(request.specify_collection, request.specify_user, spquery)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 377, in run_ephemeral_query
    field_specs, limit, offset, recordsetid, formatauditobjs=format_audits)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 442, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid=recordsetid, formatauditobjs=formatauditobjs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 505, in build_query
    query, field = fs.add_to_query(query, formatauditobjs=formatauditobjs)
TypeError: add_to_query() got an unexpected keyword argument 'formatauditobjs'
[20/Jan/2020 09:02:42] "POST /stored_query/ephemeral/ HTTP/1.1" 500 7205
```

and this:

```
Internal Server Error: /stored_query/ephemeral/
Traceback (most recent call last):
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/views.py", line 56, in ephemeral
    data = run_ephemeral_query(request.specify_collection, request.specify_user, spquery)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 377, in run_ephemeral_query
    field_specs, limit, offset, recordsetid, formatauditobjs=format_audits)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 442, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid=recordsetid, formatauditobjs=formatauditobjs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 505, in build_query
    query, field = fs.add_to_query(query, formatauditobjs=formatauditobjs)
TypeError: add_to_query() got an unexpected keyword argument 'formatauditobjs'
[20/Jan/2020 09:02:42] "POST /stored_query/ephemeral/ HTTP/1.1" 500 7205
```

**Comment by maxxxxxdlp** [comment]
The table seems to be created when I use `mysql`, but is not created when I use `mariadb`

I have exported that table from  `mysql` and executed the following query in `mariadb` installation:
```sql
CREATE TABLE `notifications_message` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timestampcreated` datetime(6) NOT NULL,
  `content` longtext NOT NULL,
  `user_id` int(11) NOT NULL,
  `read` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `notifications_mess_user_id_89f939e6_fk_specifyuser_specifyuserid` (`user_id`),
  CONSTRAINT `notifications_mess_user_id_89f939e6_fk_specifyuser_specifyuserid` FOREIGN KEY (`user_id`) REFERENCES `specifyuser` (`SpecifyUserID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
As a result, I still get `TypeError: add_to_query() got an unexpected keyword argument 'formatauditobjs'` error and the user still gets error message that stops the app from working

**Comment by benanhalt** [comment]
The notifications table should be added by a step in the setup process here: https://github.com/specify/specify7#make-django_migrations

If you are switching databases, you will need to run that step before trying to use Specify 7 on a database.

I don't know what is up with the `formatauditobjs`. That looks like something to do with Tim's auditing stuff. Which branch are you testing on?

**Comment by maxxxxxdlp** [comment]
@benanhalt I am testing everything on the `develop` branch
