### ISSUE TITLE
Error when running a query

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#587]
Error happens when running any kind of query or creating a record set out of a query

![Screenshot from 2020-01-20 09-10-45](https://user-images.githubusercontent.com/40512816/72745524-cbc9f480-3b64-11ea-828c-270b132edc5c.png)

```
Traceback (most recent call last):
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/views.py", line 56, in ephemeral
    data = run_ephemeral_query(request.specify_collection, request.specify_user, spquery)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 377, in run_ephemeral_query
    field_specs, limit, offset, recordsetid, formatauditobjs=format_audits)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 442, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid=recordsetid, formatauditobjs=formatauditobjs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 505, in build_query
    query, field = fs.add_to_query(query, formatauditobjs=formatauditobjs)
TypeError: add_to_query() got an unexpected keyword argument 'formatauditobjs'
[20/Jan/2020 11:09:58] "POST /stored_query/ephemeral/ HTTP/1.1" 500 7223
Internal Server Error: /stored_query/ephemeral/
Traceback (most recent call last):
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/views.py", line 56, in ephemeral
    data = run_ephemeral_query(request.specify_collection, request.specify_user, spquery)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 377, in run_ephemeral_query
    field_specs, limit, offset, recordsetid, formatauditobjs=format_audits)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 442, in execute
    query, order_by_exprs = build_query(session, collection, user, tableid, field_specs, recordsetid=recordsetid, formatauditobjs=formatauditobjs)
  File "/home/specify/Downloads/specify7/specifyweb/stored_queries/execution.py", line 505, in build_query
    query, field = fs.add_to_query(query, formatauditobjs=formatauditobjs)
TypeError: add_to_query() got an unexpected keyword argument 'formatauditobjs'
[20/Jan/2020 11:09:58] "POST /stored_query/ephemeral/ HTTP/1.1" 500 7217
```

**Comment by tlammer** [comment]
Can we check this again.  Any query?

**Comment by maxxxxxdlp** [comment]
It does not happen when tested on the biwebdbtest.nhm.ku.edu. Probably I have misconfigured my local Specify 7. I had a lot of issues with it that did not happen anywhere else

---

<img width="1440" alt="Screen Shot 2020-03-10 at 7 58 39 AM" src="https://user-images.githubusercontent.com/40512816/76314766-68775b80-62a5-11ea-9040-06dd0655073f.png">

---

<img width="1440" alt="Screen Shot 2020-03-10 at 8 01 08 AM" src="https://user-images.githubusercontent.com/40512816/76314771-6ad9b580-62a5-11ea-96b5-1f7145b85a62.png">
