### ISSUE TITLE
Exception when moving unparented nodes

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#736]
```
Internal Server Error: /api/specify_tree/taxon/24675/move/
Traceback (most recent call last):
  File "/home/specify/servers/dfo-arc/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/servers/dfo-arc/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/servers/dfo-arc/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/servers/dfo-arc/Specify7/ve/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/servers/dfo-arc/Specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/dfo-arc/Specify7/ve/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/specify/servers/dfo-arc/Specify7/specifyweb/specify/views.py", line 30, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/dfo-arc/Specify7/ve/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/specify/servers/dfo-arc/Specify7/specifyweb/specify/tree_views.py", line 29, in wrapper
    mutation(*args, **kwargs)
  File "/home/specify/servers/dfo-arc/Specify7/specifyweb/specify/tree_views.py", line 247, in move
    old_parentid = old_parent.id
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by melton-jason** [comment]
To further clarify, this issue is regarding moving 'root' level nodes? 
(I.e., nodes that have no parents)

**Comment by maxxxxxdlp** [comment]
Looking at the data model, there is nothing preventing non-root nodes from not having a parent (though, that would be invalid). I'm not sure how that would happen in practice that (though, there are plenty of weird broken trees out there)
