### ISSUE TITLE
Attempting to delete an attachment record that has attachmentlocation = null throws an exception.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#775]
```
Internal Server Error: /api/specify/collectionobject/179816/
Traceback (most recent call last):
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/specify/views.py", line 30, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/specify/views.py", line 44, in view
    return dispatch_func(request, *args, **kwargs)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/specify/api.py", line 112, in resource_dispatch
    model, id, version, data)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/specify/api.py", line 568, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/specify/api.py", line 592, in update_obj
    handle_to_many(collection, agent, obj, data)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/specify/api.py", line 537, in handle_to_many
    to_delete.delete()
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/db/models/query.py", line 711, in delete
    deleted, _rows_count = collector.delete()
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/db/models/deletion.py", line 318, in delete
    sender=model, instance=obj, using=self.using
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/businessrules/orm_signal_handler.py", line 19, in handler
    rule(sender, kwargs['instance'])
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/businessrules/attachment_rules.py", line 31, in attachment_jointable_deletion
    obj.attachment.delete()
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/db/models/base.py", line 919, in delete
    return collector.delete()
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/db/models/deletion.py", line 318, in delete
    sender=model, instance=obj, using=self.using
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/specify/servers/bishopmuseum/Specify7/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/businessrules/orm_signal_handler.py", line 15, in handler
    rule(kwargs['instance'])
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/businessrules/attachment_rules.py", line 43, in attachment_deletion
    delete_attachment_file(attachment.attachmentlocation)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/attachment_gw/views.py", line 68, in delete_attachment_file
    'token': generate_token(get_timestamp(), attch_loc)
  File "/home/specify/servers/bishopmuseum/Specify7/specifyweb/attachment_gw/views.py", line 77, in generate_token
    msg = str(timestamp).encode() + filename.encode()
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by emenslin** [comment]
Fixed
