### ISSUE TITLE
Paleocontext always treated as embedded by the server when connected to collection object.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#841]
Results in the following exception when attempting to create new collection objects when paleocontext is set to shared:
```
Internal Server Error: /api/specify/collectionobject/
Traceback (most recent call last):
  File "/home/specify/servers/calvertmarinemuseum/Specify7/ve/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/ve/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/ve/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/specifyweb/specify/views.py", line 30, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/specifyweb/specify/views.py", line 44, in view
    return dispatch_func(request, *args, **kwargs)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/specifyweb/specify/api.py", line 180, in collection_dispatch
    request.GET.get('recordsetid', None))
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/specifyweb/specify/api.py", line 266, in post_resource
    obj = create_obj(collection, agent, name, data)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/specifyweb/specify/api.py", line 338, in create_obj
    handle_fk_fields(collection, agent, obj, data)
  File "/home/specify/servers/calvertmarinemuseum/Specify7/specifyweb/specify/api.py", line 457, in handle_fk_fields
    assert not dependent, "didn't get inline data for dependent field %s in %s: %r" % (field_name, obj, val)
AssertionError: didn't get inline data for dependent field paleocontext in Collectionobject object (None): '/api/specify/paleocontext/1614/'
```

**Comment by maxxxxxdlp** [comment]
Can you send me a database with embeddedPaleoContext=true and paleo context subform on the co form?

**Comment by benanhalt** [comment]
I think calvertmarinemuseum which should have backups on the shared drive was the database where this issue was occuring.

**Comment by maxxxxxdlp** [comment]
Hmm, I found 3 databases in their folder. One did not load in specify 7 even after running migrations.
Another one has `embeddedPaleoContext: false` in domain.json.
I am afraid the third database is going to be the same way

**Comment by benanhalt** [comment]
Try the most recent backup from /Specify7/SpecifyCloudBackups

**Comment by maxxxxxdlp** [comment]
Hmm, it still has `embeddedPaleoContext: false` in domain.json

**Comment by benanhalt** [comment]
I think that's what you want. The bug is that it treats it as embedded regardless of the setting. But you can try switching it back and forth by changing `ispaleocontextembedded` column in `discipline` in the database.

**Comment by maxxxxxdlp** [comment]
Flipping that value back and forth and creating a new CO with Paleo Context did not throw errors.
I was able to reproduce the original error by manually reverting the commit
