### ISSUE TITLE
Timestamp fields in queries cause exception

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#868]
Bug was introduced in 110e051236a8c3634bb1c481c29ce6edef801c15

**Comment by benanhalt** [comment]
The exception:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ben/src/specify/specify7/next-release/ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ben/src/specify/specify7/next-release/ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ben/src/specify/specify7/next-release/ve/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ben/src/specify/specify7/next-release/ve/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/ben/src/specify/specify7/next-release/specifyweb/export/management/commands/make_dwca.py", line 46, in handle
    make_dwca(collection, user, definition, kwargs['output_file'], eml=eml)
  File "/home/ben/src/specify/specify7/next-release/specifyweb/export/dwca.py", line 214, in make_dwca
    strip_id=True, row_filter=collect_ids)
  File "/home/ben/src/specify/specify7/next-release/specifyweb/stored_queries/execution.py", line 160, in query_to_csv
    query, __ = build_query(session, collection, user, tableid, field_specs, recordsetid, replace_nulls=True)
  File "/home/ben/src/specify/specify7/next-release/specifyweb/stored_queries/execution.py", line 507, in build_query
    query = query.add_columns(query.objectformatter.fieldformat(fs, field))
  File "/home/ben/src/specify/specify7/next-release/specifyweb/stored_queries/format.py", line 174, in fieldformat
    field = self._dateformat(field_spec.get_field(), field)
  File "/home/ben/src/specify/specify7/next-release/specifyweb/stored_queries/format.py", line 188, in _dateformat
    prec_fld = getattr(field.class_, specify_field.name + 'Precision', None)
  File "/home/ben/src/specify/specify7/next-release/ve/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 690, in __getattr__
    key)
AttributeError: Neither 'Function' object nor 'Comparator' object has an attribute 'class_'
```

**Comment by benanhalt** [comment]
For testing: the bug causes queries that include timestamp(created|modified) to produce the above exception.
