### ISSUE TITLE
NPE in interactions business rules when creating (loan)preparation with null values for quantities.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#946]
```
Task specifyweb.workbench.tasks.upload[8896c684-fc74-422f-a922-377368380c5c] raised unexpected: TypeError("unsupported operand type(s) for -: 'int' and 'NoneType'",)
Traceback (most recent call last):
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/tasks.py", line 41, in upload
    do_upload_dataset(collection, uploading_agent_id, ds, no_commit, allow_partial, progress)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload.py", line 114, in do_upload_dataset
    results = do_upload(collection, rows, upload_plan, uploading_agent_id, disambiguation, no_commit, allow_partial, progress)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload.py", line 186, in do_upload
    result = UploadResult(bind_result, {}, {}) if isinstance(bind_result, ParseFailures) else bind_result.process_row()
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 202, in process_row
    return self._handle_row(force_upload=False)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 263, in _handle_row
    return self._do_upload(model, toOneResults, info)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 370, in _do_upload
    sorted(self.toMany.items(), key=lambda kv: kv[0]) # make the upload order deterministic
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 369, in <dictcomp>
    for fieldname, records in
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 437, in _upload_to_manys
    for record in records
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 437, in <listcomp>
    for record in records
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 205, in force_upload_row
    return self._handle_row(force_upload=True)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 263, in _handle_row
    return self._do_upload(model, toOneResults, info)
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 359, in _do_upload
    **{ model._meta.get_field(fieldname).attname: id for fieldname, id in toOneIds.items() },
  File "/home/ben/src/specify/seven/next-release/specifyweb/workbench/upload/upload_table.py", line 375, in _do_insert
    return model.objects.create(**attrs)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ben/src/specify/seven/next-release/specifyweb/specify/build_models.py", line 55, in save
    return super(model, self).save(*args, **kwargs)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/django/db/models/base.py", line 766, in save_base
    update_fields=update_fields,
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/ben/src/specify/seven/next-release/ve/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/ben/src/specify/seven/next-release/specifyweb/businessrules/orm_signal_handler.py", line 15, in handler
    rule(kwargs['instance'])
  File "/home/ben/src/specify/seven/next-release/specifyweb/businessrules/interaction_rules.py", line 34, in loanprep_quantity_must_be_lte_availability
    if available < (ipreparation.quantity - ipreparation.quantityresolved):
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by tlammer** [comment]
Quantity should be required when it is linking to an existing preparation.
